// swift-tools-version: 6.2
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import PackageDescription

let package = Package(
  name: "GoogleCloudAssetV1",
  platforms: [.macOS(.v15)],
  products: [
    .library(name: "GoogleCloudAssetV1", targets: ["GoogleCloudAssetV1"])
  ],
  dependencies: [
    .package(path: "../../packages/auth"),
    .package(path: "../../packages/gax"),
    .package(path: "../../generated/google-cloud-osconfig-v1"),
    .package(path: "../../generated/google-cloud-orgpolicy-v1"),
    .package(path: "../../packages/wkt"),
    .package(path: "../../generated/google-iam-v1"),
    .package(path: "../../generated/google-identity-accesscontextmanager-v1"),
    .package(path: "../../generated/google-longrunning"),
    .package(path: "../../generated/google-rpc"),
    .package(path: "../../generated/google-type"),
    .package(url: "https://github.com/apple/swift-log", from: "1.12.0"),
  ],
  targets: [
    .target(
      name: "GoogleCloudAssetV1",
      dependencies: [
        .product(name: "GoogleCloudAuth", package: "auth"),
        .product(name: "GoogleCloudGax", package: "gax"),
        .product(name: "GoogleCloudOSConfigV1", package: "google-cloud-osconfig-v1"),
        .product(name: "GoogleCloudOrgPolicyV1", package: "google-cloud-orgpolicy-v1"),
        .product(name: "GoogleCloudWkt", package: "wkt"),
        .product(name: "GoogleIAMV1", package: "google-iam-v1"),
        .product(
          name: "GoogleIdentityAccessContextManagerV1",
          package: "google-identity-accesscontextmanager-v1"),
        .product(name: "GoogleLongrunning", package: "google-longrunning"),
        .product(name: "GoogleRpc", package: "google-rpc"),
        .product(name: "GoogleType", package: "google-type"),
        .product(name: "Logging", package: "swift-log"),
      ],
    )
  ]
)
