// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleType

/// This organization policy message is a modified version of the one defined in
/// the Organization Policy system. This message contains several fields defined
/// in the original organization policy with some new fields for analysis
/// purpose.
public struct AnalyzerOrgPolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The [full resource name]
  /// (https://cloud.google.com/asset-inventory/docs/resource-name-format) of
  /// an organization/folder/project resource where this organization policy is
  /// set.
  ///
  /// Notice that some type of constraints are defined with default policy. This
  /// field will be empty for them.
  public var attachedResource: Swift.String = Swift.String()

  /// The [full resource name]
  /// (https://cloud.google.com/asset-inventory/docs/resource-name-format) of
  /// an organization/folder/project resource where this organization policy
  /// applies to.
  ///
  /// For any user defined org policies, this field has the same value as
  /// the [attached_resource] field. Only for default policy, this field has
  /// the different value.
  public var appliedResource: Swift.String = Swift.String()

  /// List of rules for this organization policy.
  public var rules: [AnalyzerOrgPolicy.Rule] = []

  /// If `inherit_from_parent` is true, Rules set higher up in the
  /// hierarchy (up to the closest root) are inherited and present in the
  /// effective policy. If it is false, then no rules are inherited, and this
  /// policy becomes the effective root for evaluation.
  public var inheritFromParent: Swift.Bool = Swift.Bool()

  /// Ignores policies set above this resource and restores the default behavior
  /// of the constraint at this resource.
  /// This field can be set in policies for either list or boolean
  /// constraints. If set, `rules` must be empty and `inherit_from_parent`
  /// must be set to false.
  public var reset: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `AnalyzerOrgPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzerOrgPolicy().with { $0.attachedResource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// This rule message is a customized version of the one defined in the
  /// Organization Policy system. In addition to the fields defined in the
  /// original organization policy, it contains additional field(s) under
  /// specific circumstances to support analysis results.
  public struct Rule: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The evaluating condition for this rule.
    public var condition: GoogleType.Expr? = nil

    /// The condition evaluation result for this rule.
    /// Only populated if it meets all the following criteria:
    ///
    /// * There is a
    /// [condition][google.cloud.asset.v1.AnalyzerOrgPolicy.Rule.condition]
    /// defined for this rule.
    /// * This rule is within
    ///   [AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer.consolidated_policy][google.cloud.asset.v1.AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer.consolidated_policy],
    ///   or
    ///   [AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset.consolidated_policy][google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset.consolidated_policy]
    ///   when the
    ///   [AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset][google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset]
    ///   has
    ///   [AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset.governed_resource][google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset.governed_resource].
    ///
    /// [google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset]: <doc:AnalyzeOrgPolicyGovernedAssetsResponse/GovernedAsset>
    /// [google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset.consolidated_policy]: <doc:AnalyzeOrgPolicyGovernedAssetsResponse/GovernedAsset/consolidatedPolicy>
    /// [google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset.governed_resource]: <doc:AnalyzeOrgPolicyGovernedAssetsResponse/GovernedAsset/OneOf_GovernedAsset/governedResource(_:)>
    /// [google.cloud.asset.v1.AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer.consolidated_policy]: <doc:AnalyzeOrgPolicyGovernedContainersResponse/GovernedContainer/consolidatedPolicy>
    /// [google.cloud.asset.v1.AnalyzerOrgPolicy.Rule.condition]: <doc:AnalyzerOrgPolicy/Rule/condition>
    public var conditionEvaluation: ConditionEvaluation? = nil

    public var kind: OneOf_Kind? = nil

    /// Initialize a new instance of `Rule`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Rule().with { $0.values = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case values = "values"
      case allowAll = "allowAll"
      case denyAll = "denyAll"
      case enforce = "enforce"
      case condition = "condition"
      case conditionEvaluation = "conditionEvaluation"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.condition = try container.decodeIfPresent(GoogleType.Expr.self, forKey: .condition)
      self.conditionEvaluation = try container.decodeIfPresent(
        ConditionEvaluation.self, forKey: .conditionEvaluation)

      var kind: OneOf_Kind? = nil
      let kindCheckAndSet = {
        if kind != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'kind'"))
        }
        kind = $0
      }
      if let values = try container.decodeIfPresent(
        AnalyzerOrgPolicy.Rule.StringValues?.self, forKey: .values)
      {
        try kindCheckAndSet(.values(values))
      }
      if let allowAll = try container.decodeIfPresent(Swift.Bool.self, forKey: .allowAll) {
        try kindCheckAndSet(.allowAll(allowAll))
      }
      if let denyAll = try container.decodeIfPresent(Swift.Bool.self, forKey: .denyAll) {
        try kindCheckAndSet(.denyAll(denyAll))
      }
      if let enforce = try container.decodeIfPresent(Swift.Bool.self, forKey: .enforce) {
        try kindCheckAndSet(.enforce(enforce))
      }
      self.kind = kind
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.condition, forKey: .condition)
      try container.encode(self.conditionEvaluation, forKey: .conditionEvaluation)

      if let choice = self.kind {
        switch choice {
        case .values(let value):
          try container.encode(value, forKey: .values)
        case .allowAll(let value):
          try container.encode(value, forKey: .allowAll)
        case .denyAll(let value):
          try container.encode(value, forKey: .denyAll)
        case .enforce(let value):
          try container.encode(value, forKey: .enforce)
        }
      }
    }

    /// The string values for the list constraints.
    public struct StringValues: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// List of values allowed at this resource.
      public var allowedValues: [Swift.String] = []

      /// List of values denied at this resource.
      public var deniedValues: [Swift.String] = []

      /// Initialize a new instance of `StringValues`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = StringValues().with { $0.allowedValues = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicy.Rule.StringValues"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public enum OneOf_Kind: Codable, Equatable, Sendable {
      /// List of values to be used for this policy rule. This field can be set
      /// only in policies for list constraints.
      indirect case values(AnalyzerOrgPolicy.Rule.StringValues?)
      /// Setting this to true means that all values are allowed. This field can
      /// be set only in Policies for list constraints.
      case allowAll(Swift.Bool)
      /// Setting this to true means that all values are denied. This field can
      /// be set only in Policies for list constraints.
      case denyAll(Swift.Bool)
      /// If `true`, then the `Policy` is enforced. If `false`, then any
      /// configuration is acceptable.
      /// This field can be set only in Policies for boolean constraints.
      case enforce(Swift.Bool)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicy.Rule"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
