// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The request message for performing resource move analysis.
public struct AnalyzeMoveRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Name of the resource to perform the analysis against.
  /// Only Google Cloud projects are supported as of today. Hence, this can only
  /// be a project ID (such as "projects/my-project-id") or a project number
  /// (such as "projects/12345").
  public var resource: Swift.String = Swift.String()

  /// Required. Name of the Google Cloud folder or organization to reparent the
  /// target resource. The analysis will be performed against hypothetically
  /// moving the resource to this specified destination parent. This can only be
  /// a folder number (such as "folders/123") or an organization number (such as
  /// "organizations/123").
  public var destinationParent: Swift.String = Swift.String()

  /// Analysis view indicating what information should be included in the
  /// analysis response. If unspecified, the default view is FULL.
  public var view: AnalyzeMoveRequest.AnalysisView = AnalyzeMoveRequest.AnalysisView()

  /// Initialize a new instance of `AnalyzeMoveRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzeMoveRequest().with { $0.resource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// View enum for supporting partial analysis responses.
  public enum AnalysisView: Codable, Equatable, Sendable {
    /// The default/unset value.
    /// The API will default to the FULL view.
    case unspecified
    /// Full analysis including all level of impacts of the specified resource
    /// move.
    case full
    /// Basic analysis only including blockers which will prevent the specified
    /// resource move at runtime.
    case basic
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .full: return 1
      case .basic: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "ANALYSIS_VIEW_UNSPECIFIED"
      case .full: return "FULL"
      case .basic: return "BASIC"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AnalysisView/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "ANALYSIS_VIEW_UNSPECIFIED": self = .unspecified
      case "FULL": self = .full
      case "BASIC": self = .basic
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AnalysisView/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .full
      case 2: self = .basic
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .full: return try container.encode(1)
      case .basic: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.AnalyzeMoveRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
