// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The organization policy constraint definition.
public struct AnalyzerOrgPolicyConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var constraintDefinition: OneOf_ConstraintDefinition? = nil

  /// Initialize a new instance of `AnalyzerOrgPolicyConstraint`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzerOrgPolicyConstraint().with { $0.googleDefinedConstraint = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case googleDefinedConstraint = "googleDefinedConstraint"
    case customConstraint = "customConstraint"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var constraintDefinition: OneOf_ConstraintDefinition? = nil
    let constraintDefinitionCheckAndSet = {
      if constraintDefinition != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'constraintDefinition'"))
      }
      constraintDefinition = $0
    }
    if let googleDefinedConstraint = try container.decodeIfPresent(
      AnalyzerOrgPolicyConstraint.Constraint?.self, forKey: .googleDefinedConstraint)
    {
      try constraintDefinitionCheckAndSet(.googleDefinedConstraint(googleDefinedConstraint))
    }
    if let customConstraint = try container.decodeIfPresent(
      AnalyzerOrgPolicyConstraint.CustomConstraint?.self, forKey: .customConstraint)
    {
      try constraintDefinitionCheckAndSet(.customConstraint(customConstraint))
    }
    self.constraintDefinition = constraintDefinition
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.constraintDefinition {
      switch choice {
      case .googleDefinedConstraint(let value):
        try container.encode(value, forKey: .googleDefinedConstraint)
      case .customConstraint(let value):
        try container.encode(value, forKey: .customConstraint)
      }
    }
  }

  /// The definition of a constraint.
  public struct Constraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The unique name of the constraint. Format of the name should be
    /// * `constraints/{constraint_name}`
    ///
    /// For example, `constraints/compute.disableSerialPortAccess`.
    public var name: Swift.String = Swift.String()

    /// The human readable name of the constraint.
    public var displayName: Swift.String = Swift.String()

    /// Detailed description of what this `Constraint` controls as well as how
    /// and where it is enforced.
    public var description: Swift.String = Swift.String()

    /// The evaluation behavior of this constraint in the absence of 'Policy'.
    public var constraintDefault: AnalyzerOrgPolicyConstraint.Constraint.ConstraintDefault =
      AnalyzerOrgPolicyConstraint.Constraint.ConstraintDefault()

    /// The type of restrictions for this `Constraint`.
    ///
    /// Immutable after creation.
    public var constraintType: OneOf_ConstraintType? = nil

    /// Initialize a new instance of `Constraint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Constraint().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case name = "name"
      case displayName = "displayName"
      case description = "description"
      case constraintDefault = "constraintDefault"
      case listConstraint = "listConstraint"
      case booleanConstraint = "booleanConstraint"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.name = try container.decode(Swift.String.self, forKey: .name)
      self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
      self.description = try container.decode(Swift.String.self, forKey: .description)
      self.constraintDefault = try container.decode(
        AnalyzerOrgPolicyConstraint.Constraint.ConstraintDefault.self, forKey: .constraintDefault)

      var constraintType: OneOf_ConstraintType? = nil
      let constraintTypeCheckAndSet = {
        if constraintType != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'constraintType'"))
        }
        constraintType = $0
      }
      if let listConstraint = try container.decodeIfPresent(
        AnalyzerOrgPolicyConstraint.Constraint.ListConstraint?.self, forKey: .listConstraint)
      {
        try constraintTypeCheckAndSet(.listConstraint(listConstraint))
      }
      if let booleanConstraint = try container.decodeIfPresent(
        AnalyzerOrgPolicyConstraint.Constraint.BooleanConstraint?.self, forKey: .booleanConstraint)
      {
        try constraintTypeCheckAndSet(.booleanConstraint(booleanConstraint))
      }
      self.constraintType = constraintType
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.description, forKey: .description)
      try container.encode(self.constraintDefault, forKey: .constraintDefault)

      if let choice = self.constraintType {
        switch choice {
        case .listConstraint(let value):
          try container.encode(value, forKey: .listConstraint)
        case .booleanConstraint(let value):
          try container.encode(value, forKey: .booleanConstraint)
        }
      }
    }

    /// A `Constraint` that allows or disallows a list of string values, which
    /// are configured by an organization's policy administrator with a `Policy`.
    public struct ListConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Indicates whether values grouped into categories can be used in
      /// `Policy.allowed_values` and `Policy.denied_values`. For example,
      /// `"in:Python"` would match any value in the 'Python' group.
      public var supportsIn: Swift.Bool = Swift.Bool()

      /// Indicates whether subtrees of Cloud Resource Manager resource hierarchy
      /// can be used in `Policy.allowed_values` and `Policy.denied_values`. For
      /// example, `"under:folders/123"` would match any resource under the
      /// 'folders/123' folder.
      public var supportsUnder: Swift.Bool = Swift.Bool()

      /// Initialize a new instance of `ListConstraint`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ListConstraint().with { $0.supportsIn = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.Constraint.ListConstraint"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// A `Constraint` that is either enforced or not.
    ///
    /// For example a constraint `constraints/compute.disableSerialPortAccess`.
    /// If it is enforced on a VM instance, serial port connections will not be
    /// opened to that instance.
    public struct BooleanConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Initialize a new instance of `BooleanConstraint`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = BooleanConstraint().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.Constraint.BooleanConstraint"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Specifies the default behavior in the absence of any `Policy` for the
    /// `Constraint`. This must not be `CONSTRAINT_DEFAULT_UNSPECIFIED`.
    public enum ConstraintDefault: Codable, Equatable, Sendable {
      /// This is only used for distinguishing unset values and should never be
      /// used.
      case unspecified
      /// Indicate that all values are allowed for list constraints.
      /// Indicate that enforcement is off for boolean constraints.
      case allow
      /// Indicate that all values are denied for list constraints.
      /// Indicate that enforcement is on for boolean constraints.
      case deny
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .allow: return 1
        case .deny: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "CONSTRAINT_DEFAULT_UNSPECIFIED"
        case .allow: return "ALLOW"
        case .deny: return "DENY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ConstraintDefault/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "CONSTRAINT_DEFAULT_UNSPECIFIED": self = .unspecified
        case "ALLOW": self = .allow
        case "DENY": self = .deny
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ConstraintDefault/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .allow
        case 2: self = .deny
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .allow: return try container.encode(1)
        case .deny: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// The type of restrictions for this `Constraint`.
    ///
    /// Immutable after creation.
    public enum OneOf_ConstraintType: Codable, Equatable, Sendable {
      /// Defines this constraint as being a ListConstraint.
      indirect case listConstraint(AnalyzerOrgPolicyConstraint.Constraint.ListConstraint?)
      /// Defines this constraint as being a BooleanConstraint.
      indirect case booleanConstraint(AnalyzerOrgPolicyConstraint.Constraint.BooleanConstraint?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.Constraint"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The definition of a custom constraint.
  public struct CustomConstraint: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Name of the constraint. This is unique within the organization. Format of
    /// the name should be
    /// * `organizations/{organization_id}/customConstraints/{custom_constraint_id}`
    ///
    /// Example :
    /// "organizations/123/customConstraints/custom.createOnlyE2TypeVms"
    public var name: Swift.String = Swift.String()

    /// The Resource Instance type on which this policy applies to. Format will
    /// be of the form : "<canonical service name>/<type>" Example:
    ///  * `compute.googleapis.com/Instance`.
    public var resourceTypes: [Swift.String] = []

    /// All the operations being applied for this constraint.
    public var methodTypes: [AnalyzerOrgPolicyConstraint.CustomConstraint.MethodType] = []

    /// Organization Policy condition/expression. For example:
    /// `resource.instanceName.matches("[production|test]_.*_(\d)+")'` or,
    /// `resource.management.auto_upgrade == true`
    public var condition: Swift.String = Swift.String()

    /// Allow or deny type.
    public var actionType: AnalyzerOrgPolicyConstraint.CustomConstraint.ActionType =
      AnalyzerOrgPolicyConstraint.CustomConstraint.ActionType()

    /// One line display name for the UI.
    public var displayName: Swift.String = Swift.String()

    /// Detailed information about this custom policy constraint.
    public var description: Swift.String = Swift.String()

    /// Initialize a new instance of `CustomConstraint`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CustomConstraint().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// The operation in which this constraint will be applied. For example:
    /// If the constraint applies only when create VMs, the method_types will be
    /// "CREATE" only. If the constraint applied when create or delete VMs, the
    /// method_types will be "CREATE" and "DELETE".
    public enum MethodType: Codable, Equatable, Sendable {
      /// Unspecified. Will results in user error.
      case unspecified
      /// Constraint applied when creating the resource.
      case create
      /// Constraint applied when updating the resource.
      case update
      /// Constraint applied when deleting the resource.
      case delete
      /// Constraint applied when removing an IAM grant.
      case removeGrant
      /// Constraint applied when enforcing forced tagging.
      case governTags
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .create: return 1
        case .update: return 2
        case .delete: return 3
        case .removeGrant: return 4
        case .governTags: return 5
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "METHOD_TYPE_UNSPECIFIED"
        case .create: return "CREATE"
        case .update: return "UPDATE"
        case .delete: return "DELETE"
        case .removeGrant: return "REMOVE_GRANT"
        case .governTags: return "GOVERN_TAGS"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MethodType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "METHOD_TYPE_UNSPECIFIED": self = .unspecified
        case "CREATE": self = .create
        case "UPDATE": self = .update
        case "DELETE": self = .delete
        case "REMOVE_GRANT": self = .removeGrant
        case "GOVERN_TAGS": self = .governTags
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MethodType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .create
        case 2: self = .update
        case 3: self = .delete
        case 4: self = .removeGrant
        case 5: self = .governTags
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .create: return try container.encode(1)
        case .update: return try container.encode(2)
        case .delete: return try container.encode(3)
        case .removeGrant: return try container.encode(4)
        case .governTags: return try container.encode(5)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Allow or deny type.
    public enum ActionType: Codable, Equatable, Sendable {
      /// Unspecified. Will results in user error.
      case unspecified
      /// Allowed action type.
      case allow
      /// Deny action type.
      case deny
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .allow: return 1
        case .deny: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ACTION_TYPE_UNSPECIFIED"
        case .allow: return "ALLOW"
        case .deny: return "DENY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ActionType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ACTION_TYPE_UNSPECIFIED": self = .unspecified
        case "ALLOW": self = .allow
        case "DENY": self = .deny
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ActionType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .allow
        case 2: self = .deny
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .allow: return try container.encode(1)
        case .deny: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicyConstraint.CustomConstraint"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public enum OneOf_ConstraintDefinition: Codable, Equatable, Sendable {
    /// The definition of the canned constraint defined by Google.
    indirect case googleDefinedConstraint(AnalyzerOrgPolicyConstraint.Constraint?)
    /// The definition of the custom constraint.
    indirect case customConstraint(AnalyzerOrgPolicyConstraint.CustomConstraint?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.AnalyzerOrgPolicyConstraint"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
