// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A request message for
/// [AssetService.AnalyzeIamPolicy][google.cloud.asset.v1.AssetService.AnalyzeIamPolicy].
///
/// [google.cloud.asset.v1.AssetService.AnalyzeIamPolicy]: <doc:AssetServiceClient/analyzeIamPolicy(request:)>
public struct AnalyzeIamPolicyRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The request query.
  public var analysisQuery: IamPolicyAnalysisQuery? = nil

  /// Optional. The name of a saved query, which must be in the format of:
  ///
  /// * projects/project_number/savedQueries/saved_query_id
  /// * folders/folder_number/savedQueries/saved_query_id
  /// * organizations/organization_number/savedQueries/saved_query_id
  ///
  /// If both `analysis_query` and `saved_analysis_query` are provided, they
  /// will be merged together with the `saved_analysis_query` as base and
  /// the `analysis_query` as overrides. For more details of the merge behavior,
  /// refer to the
  /// [MergeFrom](https://developers.google.com/protocol-buffers/docs/reference/cpp/google.protobuf.message#Message.MergeFrom.details)
  /// page.
  ///
  /// Note that you cannot override primitive fields with default value, such as
  /// 0 or empty string, etc., because we use proto3, which doesn't support field
  /// presence yet.
  public var savedAnalysisQuery: Swift.String = Swift.String()

  /// Optional. Amount of time executable has to complete.  See JSON
  /// representation of
  /// [Duration](https://developers.google.com/protocol-buffers/docs/proto3#json).
  ///
  /// If this field is set with a value less than the RPC deadline, and the
  /// execution of your query hasn't finished in the specified
  /// execution timeout,  you will get a response with partial result.
  /// Otherwise, your query's execution will continue until the RPC deadline.
  /// If it's not finished until then, you will get a  DEADLINE_EXCEEDED error.
  ///
  /// Default is empty.
  public var executionTimeout: GoogleCloudWkt.Duration? = nil

  /// Initialize a new instance of `AnalyzeIamPolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzeIamPolicyRequest().with { $0.analysisQuery = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.AnalyzeIamPolicyRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
