// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A request message for
/// [AssetService.AnalyzeOrgPolicies][google.cloud.asset.v1.AssetService.AnalyzeOrgPolicies].
///
/// [google.cloud.asset.v1.AssetService.AnalyzeOrgPolicies]: <doc:AssetServiceClient/analyzeOrgPolicies(request:options:)>
public struct AnalyzeOrgPoliciesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The organization to scope the request. Only organization
  /// policies within the scope will be analyzed.
  ///
  /// * organizations/{ORGANIZATION_NUMBER} (e.g., "organizations/123456")
  public var scope: Swift.String = Swift.String()

  /// Required. The name of the constraint to analyze organization policies for.
  /// The response only contains analyzed organization policies for the provided
  /// constraint.
  public var constraint: Swift.String = Swift.String()

  /// The expression to filter
  /// [AnalyzeOrgPoliciesResponse.org_policy_results][google.cloud.asset.v1.AnalyzeOrgPoliciesResponse.org_policy_results].
  /// Filtering is currently available for bare literal values and the following
  /// fields:
  /// * consolidated_policy.attached_resource
  /// * consolidated_policy.rules.enforce
  ///
  /// When filtering by a specific field, the only supported operator is `=`.
  /// For example, filtering by
  /// consolidated_policy.attached_resource="//cloudresourcemanager.googleapis.com/folders/001"
  /// will return all the Organization Policy results attached to "folders/001".
  ///
  /// [google.cloud.asset.v1.AnalyzeOrgPoliciesResponse.org_policy_results]: <doc:AnalyzeOrgPoliciesResponse/orgPolicyResults>
  public var filter: Swift.String = Swift.String()

  /// The maximum number of items to return per page. If unspecified,
  /// [AnalyzeOrgPoliciesResponse.org_policy_results][google.cloud.asset.v1.AnalyzeOrgPoliciesResponse.org_policy_results]
  /// will contain 20 items with a maximum of 200.
  ///
  /// [google.cloud.asset.v1.AnalyzeOrgPoliciesResponse.org_policy_results]: <doc:AnalyzeOrgPoliciesResponse/orgPolicyResults>
  public var pageSize: Swift.Int32? = nil

  /// The pagination token to retrieve the next page.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `AnalyzeOrgPoliciesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzeOrgPoliciesRequest().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.AnalyzeOrgPoliciesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
