// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A request message for
/// [AssetService.AnalyzeOrgPolicyGovernedAssets][google.cloud.asset.v1.AssetService.AnalyzeOrgPolicyGovernedAssets].
///
/// [google.cloud.asset.v1.AssetService.AnalyzeOrgPolicyGovernedAssets]: <doc:AssetService/analyzeOrgPolicyGovernedAssets(request:)>
public struct AnalyzeOrgPolicyGovernedAssetsRequest: Codable, Equatable, GoogleCloudWkt
    ._AnyPackable,
  Sendable
{
  /// Required. The organization to scope the request. Only organization
  /// policies within the scope will be analyzed. The output assets will
  /// also be limited to the ones governed by those in-scope organization
  /// policies.
  ///
  /// * organizations/{ORGANIZATION_NUMBER} (e.g., "organizations/123456")
  public var scope: Swift.String = Swift.String()

  /// Required. The name of the constraint to analyze governed assets for. The
  /// analysis only contains analyzed organization policies for the provided
  /// constraint.
  public var constraint: Swift.String = Swift.String()

  /// The expression to filter
  /// [AnalyzeOrgPolicyGovernedAssetsResponse.governed_assets][google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.governed_assets].
  ///
  /// For governed resources, filtering is currently available for bare literal
  /// values and the following fields:
  /// * governed_resource.project
  /// * governed_resource.folders
  /// * consolidated_policy.rules.enforce
  /// When filtering by `governed_resource.project` or
  /// `consolidated_policy.rules.enforce`, the only supported operator is `=`.
  /// When filtering by `governed_resource.folders`, the supported operators
  /// are `=` and `:`.
  /// For example, filtering by `governed_resource.project="projects/12345678"`
  /// will return all the governed resources under "projects/12345678",
  /// including the project itself if applicable.
  ///
  /// For governed IAM policies, filtering is currently available for bare
  /// literal values and the following fields:
  /// * governed_iam_policy.project
  /// * governed_iam_policy.folders
  /// * consolidated_policy.rules.enforce
  /// When filtering by `governed_iam_policy.project` or
  /// `consolidated_policy.rules.enforce`, the only supported operator is `=`.
  /// When filtering by `governed_iam_policy.folders`, the supported operators
  /// are `=` and `:`.
  /// For example, filtering by `governed_iam_policy.folders:"folders/12345678"`
  /// will return all the governed IAM policies under "folders/001".
  ///
  /// [google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.governed_assets]: <doc:AnalyzeOrgPolicyGovernedAssetsResponse/governedAssets>
  public var filter: Swift.String = Swift.String()

  /// The maximum number of items to return per page. If unspecified,
  /// [AnalyzeOrgPolicyGovernedAssetsResponse.governed_assets][google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.governed_assets]
  /// will contain 100 items with a maximum of 200.
  ///
  /// [google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsResponse.governed_assets]: <doc:AnalyzeOrgPolicyGovernedAssetsResponse/governedAssets>
  public var pageSize: Swift.Int32? = nil

  /// The pagination token to retrieve the next page.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `AnalyzeOrgPolicyGovernedAssetsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AnalyzeOrgPolicyGovernedAssetsRequest().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.AnalyzeOrgPolicyGovernedAssetsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
