// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol AssetServiceStub {
    func exportAssets(
      request: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listAssets(
      request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListAssetsResponse

    func batchGetAssetsHistory(
      request: BatchGetAssetsHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse

    func createFeed(
      request: CreateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    func getFeed(
      request: GetFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    func listFeeds(
      request: ListFeedsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListFeedsResponse

    func updateFeed(
      request: UpdateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    func deleteFeed(
      request: DeleteFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func searchAllResources(
      request: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse

    func searchAllIamPolicies(
      request: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse

    func analyzeIamPolicy(
      request: AnalyzeIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse

    func analyzeIamPolicyLongrunning(
      request: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func analyzeMove(
      request: AnalyzeMoveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeMoveResponse

    func queryAssets(
      request: QueryAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.QueryAssetsResponse

    func createSavedQuery(
      request: CreateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    func getSavedQuery(
      request: GetSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    func listSavedQueries(
      request: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse

    func updateSavedQuery(
      request: UpdateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    func deleteSavedQuery(
      request: DeleteSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func batchGetEffectiveIamPolicies(
      request: BatchGetEffectiveIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse

    func analyzeOrgPolicies(
      request: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse

    func analyzeOrgPolicyGovernedContainers(
      request: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse

    func analyzeOrgPolicyGovernedAssets(
      request: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }

  class AssetServiceTransport: AssetServiceStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://cloudasset.googleapis.com")
    }

    public func exportAssets(
      request: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0):exportAssets"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongRunning.Operation.self, from: data)
    }

    public func listAssets(
      request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListAssetsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/assets"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.readTime, prefix: "readTime"))
      query.append(contentsOf: try encoder.encode(request.assetTypes, prefix: "assetTypes"))
      query.append(contentsOf: try encoder.encode(request.contentType, prefix: "contentType"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(
        contentsOf: try encoder.encode(request.relationshipTypes, prefix: "relationshipTypes"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.ListAssetsResponse.self, from: data)
    }

    public func batchGetAssetsHistory(
      request: BatchGetAssetsHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0):batchGetAssetsHistory"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.assetNames, prefix: "assetNames"))
      query.append(contentsOf: try encoder.encode(request.contentType, prefix: "contentType"))
      query.append(contentsOf: try encoder.encode(request.readTimeWindow, prefix: "readTimeWindow"))
      query.append(
        contentsOf: try encoder.encode(request.relationshipTypes, prefix: "relationshipTypes"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.BatchGetAssetsHistoryResponse.self, from: data)
    }

    public func createFeed(
      request: CreateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/feeds"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.Feed.self, from: data)
    }

    public func getFeed(
      request: GetFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.Feed.self, from: data)
    }

    public func listFeeds(
      request: ListFeedsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListFeedsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/feeds"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.ListFeedsResponse.self, from: data)
    }

    public func updateFeed(
      request: UpdateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.feed.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.feed.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.Feed.self, from: data)
    }

    public func deleteFeed(
      request: DeleteFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func searchAllResources(
      request: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scope as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0):searchAllResources"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.query, prefix: "query"))
      query.append(contentsOf: try encoder.encode(request.assetTypes, prefix: "assetTypes"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      query.append(contentsOf: try encoder.encode(request.readMask, prefix: "readMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.SearchAllResourcesResponse.self, from: data)
    }

    public func searchAllIamPolicies(
      request: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scope as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0):searchAllIamPolicies"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.query, prefix: "query"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.assetTypes, prefix: "assetTypes"))
      query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.SearchAllIamPoliciesResponse.self, from: data)
    }

    public func analyzeIamPolicy(
      request: AnalyzeIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.analysisQuery.map({ $0.scope }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.analysis_query.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0):analyzeIamPolicy"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.analysisQuery, prefix: "analysisQuery"))
      query.append(
        contentsOf: try encoder.encode(request.savedAnalysisQuery, prefix: "savedAnalysisQuery"))
      query.append(
        contentsOf: try encoder.encode(request.executionTimeout, prefix: "executionTimeout"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.AnalyzeIamPolicyResponse.self, from: data)
    }

    public func analyzeIamPolicyLongrunning(
      request: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.analysisQuery.map({ $0.scope }), !pathVariable0.isEmpty
        else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.analysis_query.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0):analyzeIamPolicyLongrunning"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongRunning.Operation.self, from: data)
    }

    public func analyzeMove(
      request: AnalyzeMoveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeMoveResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.resource as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
        }
        return "/v1/\(pathVariable0):analyzeMove"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(
        contentsOf: try encoder.encode(request.destinationParent, prefix: "destinationParent"))
      query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.AnalyzeMoveResponse.self, from: data)
    }

    public func queryAssets(
      request: QueryAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.QueryAssetsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0):queryAssets"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.QueryAssetsResponse.self, from: data)
    }

    public func createSavedQuery(
      request: CreateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/savedQueries"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.savedQueryId, prefix: "savedQueryId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.savedQuery {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.SavedQuery.self, from: data)
    }

    public func getSavedQuery(
      request: GetSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.SavedQuery.self, from: data)
    }

    public func listSavedQueries(
      request: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/savedQueries"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.ListSavedQueriesResponse.self, from: data)
    }

    public func updateSavedQuery(
      request: UpdateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.savedQuery.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.saved_query.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.savedQuery {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.SavedQuery.self, from: data)
    }

    public func deleteSavedQuery(
      request: DeleteSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      _ = try await self.inner.rpc(for: req).get()
    }

    public func batchGetEffectiveIamPolicies(
      request: BatchGetEffectiveIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scope as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/effectiveIamPolicies:batchGet"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.names, prefix: "names"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse.self, from: data)
    }

    public func analyzeOrgPolicies(
      request: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scope as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0):analyzeOrgPolicies"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.constraint, prefix: "constraint"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse.self, from: data)
    }

    public func analyzeOrgPolicyGovernedContainers(
      request: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scope as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0):analyzeOrgPolicyGovernedContainers"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.constraint, prefix: "constraint"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse.self, from: data)
    }

    public func analyzeOrgPolicyGovernedAssets(
      request: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.scope as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.scope' is not set or is empty")
        }
        return "/v1/\(pathVariable0):analyzeOrgPolicyGovernedAssets"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.constraint, prefix: "constraint"))
      query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse.self, from: data)
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleLongRunning.Operation.self, from: data)
    }
  }
}
