// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The enhanced metadata information for a resource.
public struct AssetEnrichment: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  public var enrichmentData: OneOf_EnrichmentData? = nil

  /// Initialize a new instance of `AssetEnrichment`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AssetEnrichment().with { $0.resourceOwners = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case resourceOwners = "resourceOwners"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var enrichmentData: OneOf_EnrichmentData? = nil
    let enrichmentDataCheckAndSet = {
      if enrichmentData != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'enrichmentData'"))
      }
      enrichmentData = $0
    }
    if let resourceOwners = try container.decodeIfPresent(
      ResourceOwners?.self, forKey: .resourceOwners)
    {
      try enrichmentDataCheckAndSet(.resourceOwners(resourceOwners))
    }
    self.enrichmentData = enrichmentData
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.enrichmentData {
      switch choice {
      case .resourceOwners(let value):
        try container.encode(value, forKey: .resourceOwners)
      }
    }
  }

  public enum OneOf_EnrichmentData: Codable, Equatable, Sendable {
    /// The resource owners for a resource.
    ///
    /// Note that this field only contains the members that have "roles/owner"
    /// role in the resource's IAM Policy.
    indirect case resourceOwners(ResourceOwners?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.AssetEnrichment"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
