// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Asset service definition.
///
/// @Snippet(path: "AssetServiceQuickstart")
public final class AssetServiceClient: Clients.AssetServiceProtocol, Sendable {
  let inner: any Clients.AssetServiceStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `AssetServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AssetServiceStub = try Clients.AssetServiceTransport(options)
    inner = Clients.AssetServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AssetServiceLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Exports assets with time and resource types to a given Cloud Storage
  /// location/BigQuery table. For Cloud Storage location destinations, the
  /// output format is newline-delimited JSON. Each line represents a
  /// [google.cloud.asset.v1.Asset][google.cloud.asset.v1.Asset] in the JSON
  /// format; for BigQuery table destinations, the output table stores the fields
  /// in asset Protobuf as columns. This API implements the
  /// [google.longrunning.Operation][google.longrunning.Operation] API, which
  /// allows you to keep track of the export. We recommend intervals of at least
  /// 2 seconds with exponential retry to poll the export operation result. For
  /// regular-size resource parent, the export operation usually finishes within
  /// 5 minutes.
  ///
  /// [google.cloud.asset.v1.Asset]: <doc:Asset>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AssetService_ExportAssets")
  public func exportAssets(
    request: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.exportAssets(request: request, options: options)
  }

  /// Exports assets with time and resource types to a given Cloud Storage
  /// location/BigQuery table. For Cloud Storage location destinations, the
  /// output format is newline-delimited JSON. Each line represents a
  /// [google.cloud.asset.v1.Asset][google.cloud.asset.v1.Asset] in the JSON
  /// format; for BigQuery table destinations, the output table stores the fields
  /// in asset Protobuf as columns. This API implements the
  /// [google.longrunning.Operation][google.longrunning.Operation] API, which
  /// allows you to keep track of the export. We recommend intervals of at least
  /// 2 seconds with exponential retry to poll the export operation result. For
  /// regular-size resource parent, the export operation usually finishes within
  /// 5 minutes.
  ///
  /// [google.cloud.asset.v1.Asset]: <doc:Asset>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AssetService_ExportAssets")
  public func exportAssets(
    withPolling: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ExportAssetsResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ExportAssetsResponse>.State in
      return try op._extractStatus(ExportAssetsResponse.self)
    }
    let rawOp = try await self.exportAssets(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ExportAssetsResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists assets with time and resource types and returns paged results in
  /// response.
  ///
  /// @Snippet(path: "AssetService_ListAssets")
  public func listAssets(
    request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.ListAssetsResponse {
    try await self.inner.listAssets(request: request, options: options)
  }

  /// Lists assets with time and resource types and returns paged results in
  /// response.
  ///
  /// @Snippet(path: "AssetService_ListAssets")
  public func listAssets(
    byItem: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Asset, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudAssetV1.ListAssetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAssets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Batch gets the update history of assets that overlap a time window.
  /// For IAM_POLICY content, this API outputs history when the asset and its
  /// attached IAM POLICY both exist. This can create gaps in the output history.
  /// Otherwise, this API outputs history with asset in both non-delete or
  /// deleted status.
  /// If a specified asset does not exist, this API returns an INVALID_ARGUMENT
  /// error.
  ///
  /// @Snippet(path: "AssetService_BatchGetAssetsHistory")
  public func batchGetAssetsHistory(
    request: BatchGetAssetsHistoryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse {
    try await self.inner.batchGetAssetsHistory(request: request, options: options)
  }

  /// Creates a feed in a parent project/folder/organization to listen to its
  /// asset updates.
  ///
  /// @Snippet(path: "AssetService_CreateFeed")
  public func createFeed(
    request: CreateFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.Feed {
    try await self.inner.createFeed(request: request, options: options)
  }

  /// Gets details about an asset feed.
  ///
  /// @Snippet(path: "AssetService_GetFeed")
  public func getFeed(
    request: GetFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.Feed {
    try await self.inner.getFeed(request: request, options: options)
  }

  /// Lists all asset feeds in a parent project/folder/organization.
  ///
  /// @Snippet(path: "AssetService_ListFeeds")
  public func listFeeds(
    request: ListFeedsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.ListFeedsResponse {
    try await self.inner.listFeeds(request: request, options: options)
  }

  /// Updates an asset feed configuration.
  ///
  /// @Snippet(path: "AssetService_UpdateFeed")
  public func updateFeed(
    request: UpdateFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.Feed {
    try await self.inner.updateFeed(request: request, options: options)
  }

  /// Deletes an asset feed.
  ///
  /// @Snippet(path: "AssetService_DeleteFeed")
  public func deleteFeed(
    request: DeleteFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteFeed(request: request, options: options)
  }

  /// Searches all Google Cloud resources within the specified scope, such as a
  /// project, folder, or organization. The caller must be granted the
  /// `cloudasset.assets.searchAllResources` permission on the desired scope,
  /// otherwise the request will be rejected.
  ///
  /// @Snippet(path: "AssetService_SearchAllResources")
  public func searchAllResources(
    request: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse {
    try await self.inner.searchAllResources(request: request, options: options)
  }

  /// Searches all Google Cloud resources within the specified scope, such as a
  /// project, folder, or organization. The caller must be granted the
  /// `cloudasset.assets.searchAllResources` permission on the desired scope,
  /// otherwise the request will be rejected.
  ///
  /// @Snippet(path: "AssetService_SearchAllResources")
  public func searchAllResources(
    byItem: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceSearchResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.searchAllResources(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Searches all IAM policies within the specified scope, such as a project,
  /// folder, or organization. The caller must be granted the
  /// `cloudasset.assets.searchAllIamPolicies` permission on the desired scope,
  /// otherwise the request will be rejected.
  ///
  /// @Snippet(path: "AssetService_SearchAllIamPolicies")
  public func searchAllIamPolicies(
    request: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse {
    try await self.inner.searchAllIamPolicies(request: request, options: options)
  }

  /// Searches all IAM policies within the specified scope, such as a project,
  /// folder, or organization. The caller must be granted the
  /// `cloudasset.assets.searchAllIamPolicies` permission on the desired scope,
  /// otherwise the request will be rejected.
  ///
  /// @Snippet(path: "AssetService_SearchAllIamPolicies")
  public func searchAllIamPolicies(
    byItem: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<IamPolicySearchResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.searchAllIamPolicies(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Analyzes IAM policies to answer which identities have what accesses on
  /// which resources.
  ///
  /// @Snippet(path: "AssetService_AnalyzeIamPolicy")
  public func analyzeIamPolicy(
    request: AnalyzeIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse {
    try await self.inner.analyzeIamPolicy(request: request, options: options)
  }

  /// Analyzes IAM policies asynchronously to answer which identities have what
  /// accesses on which resources, and writes the analysis results to a Google
  /// Cloud Storage or a BigQuery destination. For Cloud Storage destination, the
  /// output format is the JSON format that represents a
  /// [AnalyzeIamPolicyResponse][google.cloud.asset.v1.AnalyzeIamPolicyResponse].
  /// This method implements the
  /// [google.longrunning.Operation][google.longrunning.Operation], which allows
  /// you to track the operation status. We recommend intervals of at least 2
  /// seconds with exponential backoff retry to poll the operation result. The
  /// metadata contains the metadata for the long-running operation.
  ///
  /// [google.cloud.asset.v1.AnalyzeIamPolicyResponse]: <doc:AnalyzeIamPolicyResponse>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AssetService_AnalyzeIamPolicyLongrunning")
  public func analyzeIamPolicyLongrunning(
    request: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.analyzeIamPolicyLongrunning(request: request, options: options)
  }

  /// Analyzes IAM policies asynchronously to answer which identities have what
  /// accesses on which resources, and writes the analysis results to a Google
  /// Cloud Storage or a BigQuery destination. For Cloud Storage destination, the
  /// output format is the JSON format that represents a
  /// [AnalyzeIamPolicyResponse][google.cloud.asset.v1.AnalyzeIamPolicyResponse].
  /// This method implements the
  /// [google.longrunning.Operation][google.longrunning.Operation], which allows
  /// you to track the operation status. We recommend intervals of at least 2
  /// seconds with exponential backoff retry to poll the operation result. The
  /// metadata contains the metadata for the long-running operation.
  ///
  /// [google.cloud.asset.v1.AnalyzeIamPolicyResponse]: <doc:AnalyzeIamPolicyResponse>
  /// [google.longrunning.Operation]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation
  ///
  /// @Snippet(path: "AssetService_AnalyzeIamPolicyLongrunning")
  public func analyzeIamPolicyLongrunning(
    withPolling: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AnalyzeIamPolicyLongrunningResponse> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AnalyzeIamPolicyLongrunningResponse>.State in
      return try op._extractStatus(AnalyzeIamPolicyLongrunningResponse.self)
    }
    let rawOp = try await self.analyzeIamPolicyLongrunning(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<AnalyzeIamPolicyLongrunningResponse>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Analyze moving a resource to a specified destination without kicking off
  /// the actual move. The analysis is best effort depending on the user's
  /// permissions of viewing different hierarchical policies and configurations.
  /// The policies and configuration are subject to change before the actual
  /// resource migration takes place.
  ///
  /// @Snippet(path: "AssetService_AnalyzeMove")
  public func analyzeMove(
    request: AnalyzeMoveRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeMoveResponse {
    try await self.inner.analyzeMove(request: request, options: options)
  }

  /// Issue a job that queries assets using a SQL statement compatible with
  /// [BigQuery SQL](https://cloud.google.com/bigquery/docs/introduction-sql).
  ///
  /// If the query execution finishes within timeout and there's no pagination,
  /// the full query results will be returned in the `QueryAssetsResponse`.
  ///
  /// Otherwise, full query results can be obtained by issuing extra requests
  /// with the `job_reference` from the a previous `QueryAssets` call.
  ///
  /// Note, the query result has approximately 10 GB limitation enforced by
  /// [BigQuery](https://cloud.google.com/bigquery/docs/best-practices-performance-output).
  /// Queries return larger results will result in errors.
  ///
  /// @Snippet(path: "AssetService_QueryAssets")
  public func queryAssets(
    request: QueryAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.QueryAssetsResponse {
    try await self.inner.queryAssets(request: request, options: options)
  }

  /// Creates a saved query in a parent project/folder/organization.
  ///
  /// @Snippet(path: "AssetService_CreateSavedQuery")
  public func createSavedQuery(
    request: CreateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    try await self.inner.createSavedQuery(request: request, options: options)
  }

  /// Gets details about a saved query.
  ///
  /// @Snippet(path: "AssetService_GetSavedQuery")
  public func getSavedQuery(
    request: GetSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    try await self.inner.getSavedQuery(request: request, options: options)
  }

  /// Lists all saved queries in a parent project/folder/organization.
  ///
  /// @Snippet(path: "AssetService_ListSavedQueries")
  public func listSavedQueries(
    request: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse {
    try await self.inner.listSavedQueries(request: request, options: options)
  }

  /// Lists all saved queries in a parent project/folder/organization.
  ///
  /// @Snippet(path: "AssetService_ListSavedQueries")
  public func listSavedQueries(
    byItem: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SavedQuery, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listSavedQueries(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Updates a saved query.
  ///
  /// @Snippet(path: "AssetService_UpdateSavedQuery")
  public func updateSavedQuery(
    request: UpdateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    try await self.inner.updateSavedQuery(request: request, options: options)
  }

  /// Deletes a saved query.
  ///
  /// @Snippet(path: "AssetService_DeleteSavedQuery")
  public func deleteSavedQuery(
    request: DeleteSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteSavedQuery(request: request, options: options)
  }

  /// Gets effective IAM policies for a batch of resources.
  ///
  /// @Snippet(path: "AssetService_BatchGetEffectiveIamPolicies")
  public func batchGetEffectiveIamPolicies(
    request: BatchGetEffectiveIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse {
    try await self.inner.batchGetEffectiveIamPolicies(request: request, options: options)
  }

  /// Analyzes organization policies under a scope.
  ///
  /// @Snippet(path: "AssetService_AnalyzeOrgPolicies")
  public func analyzeOrgPolicies(
    request: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse {
    try await self.inner.analyzeOrgPolicies(request: request, options: options)
  }

  /// Analyzes organization policies under a scope.
  ///
  /// @Snippet(path: "AssetService_AnalyzeOrgPolicies")
  public func analyzeOrgPolicies(
    byItem: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AnalyzeOrgPoliciesResponse.OrgPolicyResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.analyzeOrgPolicies(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Analyzes organization policies governed containers (projects, folders or
  /// organization) under a scope.
  ///
  /// @Snippet(path: "AssetService_AnalyzeOrgPolicyGovernedContainers")
  public func analyzeOrgPolicyGovernedContainers(
    request: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse {
    try await self.inner.analyzeOrgPolicyGovernedContainers(request: request, options: options)
  }

  /// Analyzes organization policies governed containers (projects, folders or
  /// organization) under a scope.
  ///
  /// @Snippet(path: "AssetService_AnalyzeOrgPolicyGovernedContainers")
  public func analyzeOrgPolicyGovernedContainers(
    byItem: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<
    AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer, Swift.Error
  > {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.analyzeOrgPolicyGovernedContainers(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Analyzes organization policies governed assets (Google Cloud resources or
  /// policies) under a scope. This RPC supports custom constraints and the
  /// following canned constraints:
  ///
  /// * constraints/ainotebooks.accessMode
  /// * constraints/ainotebooks.disableFileDownloads
  /// * constraints/ainotebooks.disableRootAccess
  /// * constraints/ainotebooks.disableTerminal
  /// * constraints/ainotebooks.environmentOptions
  /// * constraints/ainotebooks.requireAutoUpgradeSchedule
  /// * constraints/ainotebooks.restrictVpcNetworks
  /// * constraints/compute.disableGuestAttributesAccess
  /// * constraints/compute.disableInstanceDataAccessApis
  /// * constraints/compute.disableNestedVirtualization
  /// * constraints/compute.disableSerialPortAccess
  /// * constraints/compute.disableSerialPortLogging
  /// * constraints/compute.disableVpcExternalIpv6
  /// * constraints/compute.requireOsLogin
  /// * constraints/compute.requireShieldedVm
  /// * constraints/compute.restrictLoadBalancerCreationForTypes
  /// * constraints/compute.restrictProtocolForwardingCreationForTypes
  /// * constraints/compute.restrictXpnProjectLienRemoval
  /// * constraints/compute.setNewProjectDefaultToZonalDNSOnly
  /// * constraints/compute.skipDefaultNetworkCreation
  /// * constraints/compute.trustedImageProjects
  /// * constraints/compute.vmCanIpForward
  /// * constraints/compute.vmExternalIpAccess
  /// * constraints/gcp.detailedAuditLoggingMode
  /// * constraints/gcp.resourceLocations
  /// * constraints/iam.allowedPolicyMemberDomains
  /// * constraints/iam.automaticIamGrantsForDefaultServiceAccounts
  /// * constraints/iam.disableServiceAccountCreation
  /// * constraints/iam.disableServiceAccountKeyCreation
  /// * constraints/iam.disableServiceAccountKeyUpload
  /// * constraints/iam.restrictCrossProjectServiceAccountLienRemoval
  /// * constraints/iam.serviceAccountKeyExpiryHours
  /// * constraints/resourcemanager.accessBoundaries
  /// * constraints/resourcemanager.allowedExportDestinations
  /// * constraints/sql.restrictAuthorizedNetworks
  /// * constraints/sql.restrictNoncompliantDiagnosticDataAccess
  /// * constraints/sql.restrictNoncompliantResourceCreation
  /// * constraints/sql.restrictPublicIp
  /// * constraints/storage.publicAccessPrevention
  /// * constraints/storage.restrictAuthTypes
  /// * constraints/storage.uniformBucketLevelAccess
  ///
  /// This RPC only returns either resources of types [supported by search
  /// APIs](https://cloud.google.com/asset-inventory/docs/supported-asset-types)
  /// or IAM policies.
  ///
  /// @Snippet(path: "AssetService_AnalyzeOrgPolicyGovernedAssets")
  public func analyzeOrgPolicyGovernedAssets(
    request: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse {
    try await self.inner.analyzeOrgPolicyGovernedAssets(request: request, options: options)
  }

  /// Analyzes organization policies governed assets (Google Cloud resources or
  /// policies) under a scope. This RPC supports custom constraints and the
  /// following canned constraints:
  ///
  /// * constraints/ainotebooks.accessMode
  /// * constraints/ainotebooks.disableFileDownloads
  /// * constraints/ainotebooks.disableRootAccess
  /// * constraints/ainotebooks.disableTerminal
  /// * constraints/ainotebooks.environmentOptions
  /// * constraints/ainotebooks.requireAutoUpgradeSchedule
  /// * constraints/ainotebooks.restrictVpcNetworks
  /// * constraints/compute.disableGuestAttributesAccess
  /// * constraints/compute.disableInstanceDataAccessApis
  /// * constraints/compute.disableNestedVirtualization
  /// * constraints/compute.disableSerialPortAccess
  /// * constraints/compute.disableSerialPortLogging
  /// * constraints/compute.disableVpcExternalIpv6
  /// * constraints/compute.requireOsLogin
  /// * constraints/compute.requireShieldedVm
  /// * constraints/compute.restrictLoadBalancerCreationForTypes
  /// * constraints/compute.restrictProtocolForwardingCreationForTypes
  /// * constraints/compute.restrictXpnProjectLienRemoval
  /// * constraints/compute.setNewProjectDefaultToZonalDNSOnly
  /// * constraints/compute.skipDefaultNetworkCreation
  /// * constraints/compute.trustedImageProjects
  /// * constraints/compute.vmCanIpForward
  /// * constraints/compute.vmExternalIpAccess
  /// * constraints/gcp.detailedAuditLoggingMode
  /// * constraints/gcp.resourceLocations
  /// * constraints/iam.allowedPolicyMemberDomains
  /// * constraints/iam.automaticIamGrantsForDefaultServiceAccounts
  /// * constraints/iam.disableServiceAccountCreation
  /// * constraints/iam.disableServiceAccountKeyCreation
  /// * constraints/iam.disableServiceAccountKeyUpload
  /// * constraints/iam.restrictCrossProjectServiceAccountLienRemoval
  /// * constraints/iam.serviceAccountKeyExpiryHours
  /// * constraints/resourcemanager.accessBoundaries
  /// * constraints/resourcemanager.allowedExportDestinations
  /// * constraints/sql.restrictAuthorizedNetworks
  /// * constraints/sql.restrictNoncompliantDiagnosticDataAccess
  /// * constraints/sql.restrictNoncompliantResourceCreation
  /// * constraints/sql.restrictPublicIp
  /// * constraints/storage.publicAccessPrevention
  /// * constraints/storage.restrictAuthTypes
  /// * constraints/storage.uniformBucketLevelAccess
  ///
  /// This RPC only returns either resources of types [supported by search
  /// APIs](https://cloud.google.com/asset-inventory/docs/supported-asset-types)
  /// or IAM policies.
  ///
  /// @Snippet(path: "AssetService_AnalyzeOrgPolicyGovernedAssets")
  public func analyzeOrgPolicyGovernedAssets(
    byItem: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.analyzeOrgPolicyGovernedAssets(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AssetService_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AssetServiceClient`.
  ///
  /// To mock `AssetServiceClient` change your functions to receive
  /// `some AssetServiceProtocol` or `any AssetServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AssetServiceProtocol {
    /// See `AssetServiceClient.exportAssets`.
    func exportAssets(request: ExportAssetsRequest) async throws -> GoogleLongRunning.Operation

    /// See `AssetServiceClient.exportAssets`.
    func exportAssets(withPolling: ExportAssetsRequest) async throws -> any GoogleCloudGax
      .PollableOperation<ExportAssetsResponse>

    /// See `AssetServiceClient.listAssets`.
    func listAssets(request: ListAssetsRequest) async throws
      -> GoogleCloudAssetV1.ListAssetsResponse

    /// See `AssetServiceClient.listAssets`.
    func listAssets(
      byItem: ListAssetsRequest
    ) throws -> any AsyncSequence<Asset, Swift.Error>

    /// See `AssetServiceClient.listAssets`.
    func listAssets(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Asset, Swift.Error>

    /// See `AssetServiceClient.batchGetAssetsHistory`.
    func batchGetAssetsHistory(request: BatchGetAssetsHistoryRequest) async throws
      -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse

    /// See `AssetServiceClient.createFeed`.
    func createFeed(request: CreateFeedRequest) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.createFeed`.
    func createFeed(
      parent: Swift.String,
    ) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.getFeed`.
    func getFeed(request: GetFeedRequest) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.getFeed`.
    func getFeed(
      name: Swift.String,
    ) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.listFeeds`.
    func listFeeds(request: ListFeedsRequest) async throws -> GoogleCloudAssetV1.ListFeedsResponse

    /// See `AssetServiceClient.listFeeds`.
    func listFeeds(
      parent: Swift.String,
    ) async throws -> GoogleCloudAssetV1.ListFeedsResponse

    /// See `AssetServiceClient.updateFeed`.
    func updateFeed(request: UpdateFeedRequest) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.updateFeed`.
    func updateFeed(
      feed: Feed?,
    ) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.deleteFeed`.
    func deleteFeed(request: DeleteFeedRequest) async throws

    /// See `AssetServiceClient.deleteFeed`.
    func deleteFeed(
      name: Swift.String,
    ) async throws

    /// See `AssetServiceClient.searchAllResources`.
    func searchAllResources(request: SearchAllResourcesRequest) async throws
      -> GoogleCloudAssetV1.SearchAllResourcesResponse

    /// See `AssetServiceClient.searchAllResources`.
    func searchAllResources(
      byItem: SearchAllResourcesRequest
    ) throws -> any AsyncSequence<ResourceSearchResult, Swift.Error>

    /// See `AssetServiceClient.searchAllResources`.
    func searchAllResources(
      scope: Swift.String,
      query: Swift.String,
      assetTypes: [Swift.String],
    ) throws -> any AsyncSequence<ResourceSearchResult, Swift.Error>

    /// See `AssetServiceClient.searchAllIamPolicies`.
    func searchAllIamPolicies(request: SearchAllIamPoliciesRequest) async throws
      -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse

    /// See `AssetServiceClient.searchAllIamPolicies`.
    func searchAllIamPolicies(
      byItem: SearchAllIamPoliciesRequest
    ) throws -> any AsyncSequence<IamPolicySearchResult, Swift.Error>

    /// See `AssetServiceClient.searchAllIamPolicies`.
    func searchAllIamPolicies(
      scope: Swift.String,
      query: Swift.String,
    ) throws -> any AsyncSequence<IamPolicySearchResult, Swift.Error>

    /// See `AssetServiceClient.analyzeIamPolicy`.
    func analyzeIamPolicy(request: AnalyzeIamPolicyRequest) async throws
      -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse

    /// See `AssetServiceClient.analyzeIamPolicyLongrunning`.
    func analyzeIamPolicyLongrunning(request: AnalyzeIamPolicyLongrunningRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AssetServiceClient.analyzeIamPolicyLongrunning`.
    func analyzeIamPolicyLongrunning(withPolling: AnalyzeIamPolicyLongrunningRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AnalyzeIamPolicyLongrunningResponse>

    /// See `AssetServiceClient.analyzeMove`.
    func analyzeMove(request: AnalyzeMoveRequest) async throws
      -> GoogleCloudAssetV1.AnalyzeMoveResponse

    /// See `AssetServiceClient.queryAssets`.
    func queryAssets(request: QueryAssetsRequest) async throws
      -> GoogleCloudAssetV1.QueryAssetsResponse

    /// See `AssetServiceClient.createSavedQuery`.
    func createSavedQuery(request: CreateSavedQueryRequest) async throws
      -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.createSavedQuery`.
    func createSavedQuery(
      parent: Swift.String,
      savedQuery: SavedQuery?,
      savedQueryId: Swift.String,
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.getSavedQuery`.
    func getSavedQuery(request: GetSavedQueryRequest) async throws -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.getSavedQuery`.
    func getSavedQuery(
      name: Swift.String,
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.listSavedQueries`.
    func listSavedQueries(request: ListSavedQueriesRequest) async throws
      -> GoogleCloudAssetV1.ListSavedQueriesResponse

    /// See `AssetServiceClient.listSavedQueries`.
    func listSavedQueries(
      byItem: ListSavedQueriesRequest
    ) throws -> any AsyncSequence<SavedQuery, Swift.Error>

    /// See `AssetServiceClient.listSavedQueries`.
    func listSavedQueries(
      parent: Swift.String,
    ) throws -> any AsyncSequence<SavedQuery, Swift.Error>

    /// See `AssetServiceClient.updateSavedQuery`.
    func updateSavedQuery(request: UpdateSavedQueryRequest) async throws
      -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.updateSavedQuery`.
    func updateSavedQuery(
      savedQuery: SavedQuery?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.deleteSavedQuery`.
    func deleteSavedQuery(request: DeleteSavedQueryRequest) async throws

    /// See `AssetServiceClient.deleteSavedQuery`.
    func deleteSavedQuery(
      name: Swift.String,
    ) async throws

    /// See `AssetServiceClient.batchGetEffectiveIamPolicies`.
    func batchGetEffectiveIamPolicies(request: BatchGetEffectiveIamPoliciesRequest) async throws
      -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse

    /// See `AssetServiceClient.analyzeOrgPolicies`.
    func analyzeOrgPolicies(request: AnalyzeOrgPoliciesRequest) async throws
      -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse

    /// See `AssetServiceClient.analyzeOrgPolicies`.
    func analyzeOrgPolicies(
      byItem: AnalyzeOrgPoliciesRequest
    ) throws -> any AsyncSequence<AnalyzeOrgPoliciesResponse.OrgPolicyResult, Swift.Error>

    /// See `AssetServiceClient.analyzeOrgPolicies`.
    func analyzeOrgPolicies(
      scope: Swift.String,
      constraint: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<AnalyzeOrgPoliciesResponse.OrgPolicyResult, Swift.Error>

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedContainers`.
    func analyzeOrgPolicyGovernedContainers(request: AnalyzeOrgPolicyGovernedContainersRequest)
      async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedContainers`.
    func analyzeOrgPolicyGovernedContainers(
      byItem: AnalyzeOrgPolicyGovernedContainersRequest
    ) throws -> any AsyncSequence<
      AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer, Swift.Error
    >

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedContainers`.
    func analyzeOrgPolicyGovernedContainers(
      scope: Swift.String,
      constraint: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<
      AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer, Swift.Error
    >

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedAssets`.
    func analyzeOrgPolicyGovernedAssets(request: AnalyzeOrgPolicyGovernedAssetsRequest) async throws
      -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedAssets`.
    func analyzeOrgPolicyGovernedAssets(
      byItem: AnalyzeOrgPolicyGovernedAssetsRequest
    ) throws -> any AsyncSequence<AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset, Swift.Error>

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedAssets`.
    func analyzeOrgPolicyGovernedAssets(
      scope: Swift.String,
      constraint: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset, Swift.Error>

    /// See `AssetServiceClient.exportAssets`.
    func exportAssets(
      request: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AssetServiceClient.exportAssets`.
    func exportAssets(
      withPolling: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ExportAssetsResponse>

    /// See `AssetServiceClient.listAssets`.
    func listAssets(
      request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListAssetsResponse

    /// See `AssetServiceClient.listAssets`.
    func listAssets(
      byItem: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Asset, Swift.Error>

    /// See `AssetServiceClient.batchGetAssetsHistory`.
    func batchGetAssetsHistory(
      request: BatchGetAssetsHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse

    /// See `AssetServiceClient.createFeed`.
    func createFeed(
      request: CreateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.getFeed`.
    func getFeed(
      request: GetFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.listFeeds`.
    func listFeeds(
      request: ListFeedsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListFeedsResponse

    /// See `AssetServiceClient.updateFeed`.
    func updateFeed(
      request: UpdateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    /// See `AssetServiceClient.deleteFeed`.
    func deleteFeed(
      request: DeleteFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AssetServiceClient.searchAllResources`.
    func searchAllResources(
      request: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse

    /// See `AssetServiceClient.searchAllResources`.
    func searchAllResources(
      byItem: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ResourceSearchResult, Swift.Error>

    /// See `AssetServiceClient.searchAllIamPolicies`.
    func searchAllIamPolicies(
      request: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse

    /// See `AssetServiceClient.searchAllIamPolicies`.
    func searchAllIamPolicies(
      byItem: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<IamPolicySearchResult, Swift.Error>

    /// See `AssetServiceClient.analyzeIamPolicy`.
    func analyzeIamPolicy(
      request: AnalyzeIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse

    /// See `AssetServiceClient.analyzeIamPolicyLongrunning`.
    func analyzeIamPolicyLongrunning(
      request: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AssetServiceClient.analyzeIamPolicyLongrunning`.
    func analyzeIamPolicyLongrunning(
      withPolling: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AnalyzeIamPolicyLongrunningResponse>

    /// See `AssetServiceClient.analyzeMove`.
    func analyzeMove(
      request: AnalyzeMoveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeMoveResponse

    /// See `AssetServiceClient.queryAssets`.
    func queryAssets(
      request: QueryAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.QueryAssetsResponse

    /// See `AssetServiceClient.createSavedQuery`.
    func createSavedQuery(
      request: CreateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.getSavedQuery`.
    func getSavedQuery(
      request: GetSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.listSavedQueries`.
    func listSavedQueries(
      request: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse

    /// See `AssetServiceClient.listSavedQueries`.
    func listSavedQueries(
      byItem: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SavedQuery, Swift.Error>

    /// See `AssetServiceClient.updateSavedQuery`.
    func updateSavedQuery(
      request: UpdateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    /// See `AssetServiceClient.deleteSavedQuery`.
    func deleteSavedQuery(
      request: DeleteSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `AssetServiceClient.batchGetEffectiveIamPolicies`.
    func batchGetEffectiveIamPolicies(
      request: BatchGetEffectiveIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse

    /// See `AssetServiceClient.analyzeOrgPolicies`.
    func analyzeOrgPolicies(
      request: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse

    /// See `AssetServiceClient.analyzeOrgPolicies`.
    func analyzeOrgPolicies(
      byItem: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AnalyzeOrgPoliciesResponse.OrgPolicyResult, Swift.Error>

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedContainers`.
    func analyzeOrgPolicyGovernedContainers(
      request: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedContainers`.
    func analyzeOrgPolicyGovernedContainers(
      byItem: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<
      AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer, Swift.Error
    >

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedAssets`.
    func analyzeOrgPolicyGovernedAssets(
      request: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse

    /// See `AssetServiceClient.analyzeOrgPolicyGovernedAssets`.
    func analyzeOrgPolicyGovernedAssets(
      byItem: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset, Swift.Error>
  }
}

// Default implementations
extension Clients.AssetServiceProtocol {
  public func exportAssets(request: ExportAssetsRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.exportAssets(request: request, options: .init())
  }

  public func exportAssets(
    request: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func exportAssets(withPolling: ExportAssetsRequest) async throws -> any GoogleCloudGax
    .PollableOperation<ExportAssetsResponse>
  {
    try await self.exportAssets(withPolling: withPolling, options: .init())
  }

  public func exportAssets(
    withPolling: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ExportAssetsResponse> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ExportAssetsResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listAssets(request: ListAssetsRequest) async throws
    -> GoogleCloudAssetV1.ListAssetsResponse
  {
    try await self.listAssets(request: request, options: .init())
  }

  public func listAssets(
    request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.ListAssetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAssets(
    byItem: ListAssetsRequest
  ) throws -> any AsyncSequence<Asset, Swift.Error> {
    try self.listAssets(byItem: byItem, options: .init())
  }

  public func listAssets(
    byItem: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Asset, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleCloudAssetV1.ListAssetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAssets(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Asset, Swift.Error> {
    let request = ListAssetsRequest().with {
      $0.parent = parent
    }
    return try self.listAssets(byItem: request)
  }

  public func batchGetAssetsHistory(request: BatchGetAssetsHistoryRequest) async throws
    -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse
  {
    try await self.batchGetAssetsHistory(request: request, options: .init())
  }

  public func batchGetAssetsHistory(
    request: BatchGetAssetsHistoryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createFeed(request: CreateFeedRequest) async throws -> GoogleCloudAssetV1.Feed {
    try await self.createFeed(request: request, options: .init())
  }

  public func createFeed(
    request: CreateFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.Feed {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createFeed(
    parent: Swift.String,
  ) async throws -> GoogleCloudAssetV1.Feed {
    let request = CreateFeedRequest().with {
      $0.parent = parent
    }
    return try await self.createFeed(request: request)
  }

  public func getFeed(request: GetFeedRequest) async throws -> GoogleCloudAssetV1.Feed {
    try await self.getFeed(request: request, options: .init())
  }

  public func getFeed(
    request: GetFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.Feed {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getFeed(
    name: Swift.String,
  ) async throws -> GoogleCloudAssetV1.Feed {
    let request = GetFeedRequest().with {
      $0.name = name
    }
    return try await self.getFeed(request: request)
  }

  public func listFeeds(request: ListFeedsRequest) async throws
    -> GoogleCloudAssetV1.ListFeedsResponse
  {
    try await self.listFeeds(request: request, options: .init())
  }

  public func listFeeds(
    request: ListFeedsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.ListFeedsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listFeeds(
    parent: Swift.String,
  ) async throws -> GoogleCloudAssetV1.ListFeedsResponse {
    let request = ListFeedsRequest().with {
      $0.parent = parent
    }
    return try await self.listFeeds(request: request)
  }

  public func updateFeed(request: UpdateFeedRequest) async throws -> GoogleCloudAssetV1.Feed {
    try await self.updateFeed(request: request, options: .init())
  }

  public func updateFeed(
    request: UpdateFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.Feed {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateFeed(
    feed: Feed?,
  ) async throws -> GoogleCloudAssetV1.Feed {
    let request = UpdateFeedRequest().with {
      $0.feed = feed
    }
    return try await self.updateFeed(request: request)
  }

  public func deleteFeed(request: DeleteFeedRequest) async throws {
    try await self.deleteFeed(request: request, options: .init())
  }

  public func deleteFeed(
    request: DeleteFeedRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteFeed(
    name: Swift.String,
  ) async throws {
    let request = DeleteFeedRequest().with {
      $0.name = name
    }
    try await self.deleteFeed(request: request)
  }

  public func searchAllResources(request: SearchAllResourcesRequest) async throws
    -> GoogleCloudAssetV1.SearchAllResourcesResponse
  {
    try await self.searchAllResources(request: request, options: .init())
  }

  public func searchAllResources(
    request: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchAllResources(
    byItem: SearchAllResourcesRequest
  ) throws -> any AsyncSequence<ResourceSearchResult, Swift.Error> {
    try self.searchAllResources(byItem: byItem, options: .init())
  }

  public func searchAllResources(
    byItem: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ResourceSearchResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchAllResources(
    scope: Swift.String,
    query: Swift.String,
    assetTypes: [Swift.String],
  ) throws -> any AsyncSequence<ResourceSearchResult, Swift.Error> {
    let request = SearchAllResourcesRequest().with {
      $0.scope = scope
      $0.query = query
      $0.assetTypes = assetTypes
    }
    return try self.searchAllResources(byItem: request)
  }

  public func searchAllIamPolicies(request: SearchAllIamPoliciesRequest) async throws
    -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse
  {
    try await self.searchAllIamPolicies(request: request, options: .init())
  }

  public func searchAllIamPolicies(
    request: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchAllIamPolicies(
    byItem: SearchAllIamPoliciesRequest
  ) throws -> any AsyncSequence<IamPolicySearchResult, Swift.Error> {
    try self.searchAllIamPolicies(byItem: byItem, options: .init())
  }

  public func searchAllIamPolicies(
    byItem: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<IamPolicySearchResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchAllIamPolicies(
    scope: Swift.String,
    query: Swift.String,
  ) throws -> any AsyncSequence<IamPolicySearchResult, Swift.Error> {
    let request = SearchAllIamPoliciesRequest().with {
      $0.scope = scope
      $0.query = query
    }
    return try self.searchAllIamPolicies(byItem: request)
  }

  public func analyzeIamPolicy(request: AnalyzeIamPolicyRequest) async throws
    -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse
  {
    try await self.analyzeIamPolicy(request: request, options: .init())
  }

  public func analyzeIamPolicy(
    request: AnalyzeIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeIamPolicyLongrunning(request: AnalyzeIamPolicyLongrunningRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.analyzeIamPolicyLongrunning(request: request, options: .init())
  }

  public func analyzeIamPolicyLongrunning(
    request: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeIamPolicyLongrunning(withPolling: AnalyzeIamPolicyLongrunningRequest)
    async throws -> any GoogleCloudGax.PollableOperation<AnalyzeIamPolicyLongrunningResponse>
  {
    try await self.analyzeIamPolicyLongrunning(withPolling: withPolling, options: .init())
  }

  public func analyzeIamPolicyLongrunning(
    withPolling: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AnalyzeIamPolicyLongrunningResponse> {
    let poll = {
      () async throws
        -> GoogleCloudGax._PollableOperationImpl<AnalyzeIamPolicyLongrunningResponse>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func analyzeMove(request: AnalyzeMoveRequest) async throws
    -> GoogleCloudAssetV1.AnalyzeMoveResponse
  {
    try await self.analyzeMove(request: request, options: .init())
  }

  public func analyzeMove(
    request: AnalyzeMoveRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeMoveResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func queryAssets(request: QueryAssetsRequest) async throws
    -> GoogleCloudAssetV1.QueryAssetsResponse
  {
    try await self.queryAssets(request: request, options: .init())
  }

  public func queryAssets(
    request: QueryAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.QueryAssetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSavedQuery(request: CreateSavedQueryRequest) async throws
    -> GoogleCloudAssetV1.SavedQuery
  {
    try await self.createSavedQuery(request: request, options: .init())
  }

  public func createSavedQuery(
    request: CreateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createSavedQuery(
    parent: Swift.String,
    savedQuery: SavedQuery?,
    savedQueryId: Swift.String,
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    let request = CreateSavedQueryRequest().with {
      $0.parent = parent
      $0.savedQuery = savedQuery
      $0.savedQueryId = savedQueryId
    }
    return try await self.createSavedQuery(request: request)
  }

  public func getSavedQuery(request: GetSavedQueryRequest) async throws
    -> GoogleCloudAssetV1.SavedQuery
  {
    try await self.getSavedQuery(request: request, options: .init())
  }

  public func getSavedQuery(
    request: GetSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSavedQuery(
    name: Swift.String,
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    let request = GetSavedQueryRequest().with {
      $0.name = name
    }
    return try await self.getSavedQuery(request: request)
  }

  public func listSavedQueries(request: ListSavedQueriesRequest) async throws
    -> GoogleCloudAssetV1.ListSavedQueriesResponse
  {
    try await self.listSavedQueries(request: request, options: .init())
  }

  public func listSavedQueries(
    request: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSavedQueries(
    byItem: ListSavedQueriesRequest
  ) throws -> any AsyncSequence<SavedQuery, Swift.Error> {
    try self.listSavedQueries(byItem: byItem, options: .init())
  }

  public func listSavedQueries(
    byItem: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SavedQuery, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listSavedQueries(
    parent: Swift.String,
  ) throws -> any AsyncSequence<SavedQuery, Swift.Error> {
    let request = ListSavedQueriesRequest().with {
      $0.parent = parent
    }
    return try self.listSavedQueries(byItem: request)
  }

  public func updateSavedQuery(request: UpdateSavedQueryRequest) async throws
    -> GoogleCloudAssetV1.SavedQuery
  {
    try await self.updateSavedQuery(request: request, options: .init())
  }

  public func updateSavedQuery(
    request: UpdateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSavedQuery(
    savedQuery: SavedQuery?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleCloudAssetV1.SavedQuery {
    let request = UpdateSavedQueryRequest().with {
      $0.savedQuery = savedQuery
      $0.updateMask = updateMask
    }
    return try await self.updateSavedQuery(request: request)
  }

  public func deleteSavedQuery(request: DeleteSavedQueryRequest) async throws {
    try await self.deleteSavedQuery(request: request, options: .init())
  }

  public func deleteSavedQuery(
    request: DeleteSavedQueryRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSavedQuery(
    name: Swift.String,
  ) async throws {
    let request = DeleteSavedQueryRequest().with {
      $0.name = name
    }
    try await self.deleteSavedQuery(request: request)
  }

  public func batchGetEffectiveIamPolicies(request: BatchGetEffectiveIamPoliciesRequest)
    async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse
  {
    try await self.batchGetEffectiveIamPolicies(request: request, options: .init())
  }

  public func batchGetEffectiveIamPolicies(
    request: BatchGetEffectiveIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeOrgPolicies(request: AnalyzeOrgPoliciesRequest) async throws
    -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse
  {
    try await self.analyzeOrgPolicies(request: request, options: .init())
  }

  public func analyzeOrgPolicies(
    request: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeOrgPolicies(
    byItem: AnalyzeOrgPoliciesRequest
  ) throws -> any AsyncSequence<AnalyzeOrgPoliciesResponse.OrgPolicyResult, Swift.Error> {
    try self.analyzeOrgPolicies(byItem: byItem, options: .init())
  }

  public func analyzeOrgPolicies(
    byItem: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AnalyzeOrgPoliciesResponse.OrgPolicyResult, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func analyzeOrgPolicies(
    scope: Swift.String,
    constraint: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<AnalyzeOrgPoliciesResponse.OrgPolicyResult, Swift.Error> {
    let request = AnalyzeOrgPoliciesRequest().with {
      $0.scope = scope
      $0.constraint = constraint
      $0.filter = filter
    }
    return try self.analyzeOrgPolicies(byItem: request)
  }

  public func analyzeOrgPolicyGovernedContainers(request: AnalyzeOrgPolicyGovernedContainersRequest)
    async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse
  {
    try await self.analyzeOrgPolicyGovernedContainers(request: request, options: .init())
  }

  public func analyzeOrgPolicyGovernedContainers(
    request: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeOrgPolicyGovernedContainers(
    byItem: AnalyzeOrgPolicyGovernedContainersRequest
  ) throws -> any AsyncSequence<
    AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer, Swift.Error
  > {
    try self.analyzeOrgPolicyGovernedContainers(byItem: byItem, options: .init())
  }

  public func analyzeOrgPolicyGovernedContainers(
    byItem: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<
    AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer, Swift.Error
  > {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func analyzeOrgPolicyGovernedContainers(
    scope: Swift.String,
    constraint: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<
    AnalyzeOrgPolicyGovernedContainersResponse.GovernedContainer, Swift.Error
  > {
    let request = AnalyzeOrgPolicyGovernedContainersRequest().with {
      $0.scope = scope
      $0.constraint = constraint
      $0.filter = filter
    }
    return try self.analyzeOrgPolicyGovernedContainers(byItem: request)
  }

  public func analyzeOrgPolicyGovernedAssets(request: AnalyzeOrgPolicyGovernedAssetsRequest)
    async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse
  {
    try await self.analyzeOrgPolicyGovernedAssets(request: request, options: .init())
  }

  public func analyzeOrgPolicyGovernedAssets(
    request: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func analyzeOrgPolicyGovernedAssets(
    byItem: AnalyzeOrgPolicyGovernedAssetsRequest
  ) throws -> any AsyncSequence<AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset, Swift.Error> {
    try self.analyzeOrgPolicyGovernedAssets(byItem: byItem, options: .init())
  }

  public func analyzeOrgPolicyGovernedAssets(
    byItem: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws
        -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func analyzeOrgPolicyGovernedAssets(
    scope: Swift.String,
    constraint: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<AnalyzeOrgPolicyGovernedAssetsResponse.GovernedAsset, Swift.Error> {
    let request = AnalyzeOrgPolicyGovernedAssetsRequest().with {
      $0.scope = scope
      $0.constraint = constraint
      $0.filter = filter
    }
    return try self.analyzeOrgPolicyGovernedAssets(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
