// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax

extension Clients {
  protocol AssetServiceStub: Sendable {
    func exportAssets(
      request: ExportAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listAssets(
      request: ListAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListAssetsResponse

    func batchGetAssetsHistory(
      request: BatchGetAssetsHistoryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse

    func createFeed(
      request: CreateFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    func getFeed(
      request: GetFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    func listFeeds(
      request: ListFeedsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListFeedsResponse

    func updateFeed(
      request: UpdateFeedRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed

    func deleteFeed(
      request: DeleteFeedRequest, options: GoogleGax.RequestOptions
    ) async throws

    func searchAllResources(
      request: SearchAllResourcesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse

    func searchAllIamPolicies(
      request: SearchAllIamPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse

    func analyzeIamPolicy(
      request: AnalyzeIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse

    func analyzeIamPolicyLongrunning(
      request: AnalyzeIamPolicyLongrunningRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func analyzeMove(
      request: AnalyzeMoveRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeMoveResponse

    func queryAssets(
      request: QueryAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.QueryAssetsResponse

    func createSavedQuery(
      request: CreateSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    func getSavedQuery(
      request: GetSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    func listSavedQueries(
      request: ListSavedQueriesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse

    func updateSavedQuery(
      request: UpdateSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery

    func deleteSavedQuery(
      request: DeleteSavedQueryRequest, options: GoogleGax.RequestOptions
    ) async throws

    func batchGetEffectiveIamPolicies(
      request: BatchGetEffectiveIamPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse

    func analyzeOrgPolicies(
      request: AnalyzeOrgPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse

    func analyzeOrgPolicyGovernedContainers(
      request: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse

    func analyzeOrgPolicyGovernedAssets(
      request: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
