// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class AssetServiceLogging: AssetServiceStub {
    let inner: any AssetServiceStub
    let logger: Logger

    public init(_ inner: any AssetServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-asset-v1"
      logger[metadataKey: "gcp.client.service"] = "cloudasset"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AssetService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func exportAssets(
      request: ExportAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "exportAssets",
        action: {
          (r: ExportAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.exportAssets(request: r, options: o)
        })
    }

    public func listAssets(
      request: ListAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListAssetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAssets",
        action: {
          (r: ListAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.ListAssetsResponse
          in
          return try await self.inner.listAssets(request: r, options: o)
        })
    }

    public func batchGetAssetsHistory(
      request: BatchGetAssetsHistoryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchGetAssetsHistory",
        action: {
          (r: BatchGetAssetsHistoryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.BatchGetAssetsHistoryResponse
          in
          return try await self.inner.batchGetAssetsHistory(request: r, options: o)
        })
    }

    public func createFeed(
      request: CreateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed {
      try await self._intercept(
        request: request,
        options: options,
        name: "createFeed",
        action: {
          (r: CreateFeedRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.Feed
          in
          return try await self.inner.createFeed(request: r, options: o)
        })
    }

    public func getFeed(
      request: GetFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed {
      try await self._intercept(
        request: request,
        options: options,
        name: "getFeed",
        action: {
          (r: GetFeedRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.Feed
          in
          return try await self.inner.getFeed(request: r, options: o)
        })
    }

    public func listFeeds(
      request: ListFeedsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListFeedsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listFeeds",
        action: {
          (r: ListFeedsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.ListFeedsResponse
          in
          return try await self.inner.listFeeds(request: r, options: o)
        })
    }

    public func updateFeed(
      request: UpdateFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.Feed {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateFeed",
        action: {
          (r: UpdateFeedRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.Feed
          in
          return try await self.inner.updateFeed(request: r, options: o)
        })
    }

    public func deleteFeed(
      request: DeleteFeedRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteFeed",
        action: { (r: DeleteFeedRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteFeed(request: r, options: o)
        })
    }

    public func searchAllResources(
      request: SearchAllResourcesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllResourcesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchAllResources",
        action: {
          (r: SearchAllResourcesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.SearchAllResourcesResponse
          in
          return try await self.inner.searchAllResources(request: r, options: o)
        })
    }

    public func searchAllIamPolicies(
      request: SearchAllIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchAllIamPolicies",
        action: {
          (r: SearchAllIamPoliciesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.SearchAllIamPoliciesResponse
          in
          return try await self.inner.searchAllIamPolicies(request: r, options: o)
        })
    }

    public func analyzeIamPolicy(
      request: AnalyzeIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeIamPolicy",
        action: {
          (r: AnalyzeIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.AnalyzeIamPolicyResponse
          in
          return try await self.inner.analyzeIamPolicy(request: r, options: o)
        })
    }

    public func analyzeIamPolicyLongrunning(
      request: AnalyzeIamPolicyLongrunningRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeIamPolicyLongrunning",
        action: {
          (r: AnalyzeIamPolicyLongrunningRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.analyzeIamPolicyLongrunning(request: r, options: o)
        })
    }

    public func analyzeMove(
      request: AnalyzeMoveRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeMoveResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeMove",
        action: {
          (r: AnalyzeMoveRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.AnalyzeMoveResponse
          in
          return try await self.inner.analyzeMove(request: r, options: o)
        })
    }

    public func queryAssets(
      request: QueryAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.QueryAssetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "queryAssets",
        action: {
          (r: QueryAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.QueryAssetsResponse
          in
          return try await self.inner.queryAssets(request: r, options: o)
        })
    }

    public func createSavedQuery(
      request: CreateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSavedQuery",
        action: {
          (r: CreateSavedQueryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.SavedQuery
          in
          return try await self.inner.createSavedQuery(request: r, options: o)
        })
    }

    public func getSavedQuery(
      request: GetSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSavedQuery",
        action: {
          (r: GetSavedQueryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.SavedQuery
          in
          return try await self.inner.getSavedQuery(request: r, options: o)
        })
    }

    public func listSavedQueries(
      request: ListSavedQueriesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.ListSavedQueriesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSavedQueries",
        action: {
          (r: ListSavedQueriesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.ListSavedQueriesResponse
          in
          return try await self.inner.listSavedQueries(request: r, options: o)
        })
    }

    public func updateSavedQuery(
      request: UpdateSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.SavedQuery {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSavedQuery",
        action: {
          (r: UpdateSavedQueryRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.SavedQuery
          in
          return try await self.inner.updateSavedQuery(request: r, options: o)
        })
    }

    public func deleteSavedQuery(
      request: DeleteSavedQueryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSavedQuery",
        action: {
          (r: DeleteSavedQueryRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSavedQuery(request: r, options: o)
        })
    }

    public func batchGetEffectiveIamPolicies(
      request: BatchGetEffectiveIamPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "batchGetEffectiveIamPolicies",
        action: {
          (r: BatchGetEffectiveIamPoliciesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.BatchGetEffectiveIamPoliciesResponse
          in
          return try await self.inner.batchGetEffectiveIamPolicies(request: r, options: o)
        })
    }

    public func analyzeOrgPolicies(
      request: AnalyzeOrgPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeOrgPolicies",
        action: {
          (r: AnalyzeOrgPoliciesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.AnalyzeOrgPoliciesResponse
          in
          return try await self.inner.analyzeOrgPolicies(request: r, options: o)
        })
    }

    public func analyzeOrgPolicyGovernedContainers(
      request: AnalyzeOrgPolicyGovernedContainersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeOrgPolicyGovernedContainers",
        action: {
          (r: AnalyzeOrgPolicyGovernedContainersRequest, o: GoogleCloudGax.RequestOptions)
            async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedContainersResponse
          in
          return try await self.inner.analyzeOrgPolicyGovernedContainers(request: r, options: o)
        })
    }

    public func analyzeOrgPolicyGovernedAssets(
      request: AnalyzeOrgPolicyGovernedAssetsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "analyzeOrgPolicyGovernedAssets",
        action: {
          (r: AnalyzeOrgPolicyGovernedAssetsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleCloudAssetV1.AnalyzeOrgPolicyGovernedAssetsResponse
          in
          return try await self.inner.analyzeOrgPolicyGovernedAssets(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongrunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleLongrunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
