// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A request message for
/// [AssetService.BatchGetEffectiveIamPolicies][google.cloud.asset.v1.AssetService.BatchGetEffectiveIamPolicies].
///
/// [google.cloud.asset.v1.AssetService.BatchGetEffectiveIamPolicies]: <doc:AssetServiceClient/batchGetEffectiveIamPolicies(request:options:)>
public struct BatchGetEffectiveIamPoliciesRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Only IAM policies on or below the scope will be returned.
  ///
  /// This can only be an organization number (such as "organizations/123"), a
  /// folder number (such as "folders/123"), a project ID (such as
  /// "projects/my-project-id"), or a project number (such as "projects/12345").
  ///
  /// To know how to get organization ID, visit [here
  /// ](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).
  ///
  /// To know how to get folder or project ID, visit [here
  /// ](https://cloud.google.com/resource-manager/docs/creating-managing-folders#viewing_or_listing_folders_and_projects).
  public var scope: Swift.String = Swift.String()

  /// Required. The names refer to the [full_resource_names]
  /// (https://cloud.google.com/asset-inventory/docs/resource-name-format)
  /// of the asset types [supported by search
  /// APIs](https://cloud.google.com/asset-inventory/docs/supported-asset-types).
  /// A maximum of 20 resources' effective policies can be retrieved in a batch.
  public var names: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BatchGetEffectiveIamPoliciesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BatchGetEffectiveIamPoliciesRequest().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scope = CodingKeys(stringValue: "scope")
    static let names = CodingKeys(stringValue: "names")

    static let _knownKeys: Set<Swift.String> = [
      "scope",
      "names",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      self.scope = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .names) {
      self.names = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.scope, forKey: .scope)
    try container.encode(self.names, forKey: .names)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.BatchGetEffectiveIamPoliciesRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
