// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The effective tags and the ancestor resources from which they were inherited.
public struct EffectiveTagDetails: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The [full resource
  /// name](https://cloud.google.com/asset-inventory/docs/resource-name-format)
  /// of the ancestor from which
  /// [effective_tags][google.cloud.asset.v1.EffectiveTagDetails.effective_tags]
  /// are inherited, according to [tag
  /// inheritance](https://cloud.google.com/resource-manager/docs/tags/tags-overview#inheritance).
  ///
  /// [google.cloud.asset.v1.EffectiveTagDetails.effective_tags]: <doc:EffectiveTagDetails/effectiveTags>
  public var attachedResource: Swift.String? = nil

  /// The effective tags inherited from the
  /// [attached_resource][google.cloud.asset.v1.EffectiveTagDetails.attached_resource].
  /// Note that tags with the same key but different values may attach to
  /// resources at a different hierarchy levels. The lower hierarchy tag value
  /// will overwrite the higher hierarchy tag value of the same tag key. In this
  /// case, the tag value at the higher hierarchy level will be removed. For more
  /// information, see [tag
  /// inheritance](https://cloud.google.com/resource-manager/docs/tags/tags-overview#inheritance).
  ///
  /// [google.cloud.asset.v1.EffectiveTagDetails.attached_resource]: <doc:EffectiveTagDetails/attachedResource>
  public var effectiveTags: [Tag] = []

  /// Initialize a new instance of `EffectiveTagDetails`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EffectiveTagDetails().with { $0.attachedResource = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.EffectiveTagDetails"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
