// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The export asset response. This message is returned by the
/// [google.longrunning.Operations.GetOperation][google.longrunning.Operations.GetOperation]
/// method in the returned
/// [google.longrunning.Operation.response][google.longrunning.Operation.response]
/// field.
///
/// [google.longrunning.Operation.response]: https://www.google.com/search?q=Swift+google.longrunning+GoogleLongRunning.Operation/OneOf_Result/response(_:)
public struct ExportAssetsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Time the snapshot was taken.
  public var readTime: GoogleCloudWKT.Timestamp? = nil

  /// Output configuration indicating where the results were output to.
  public var outputConfig: OutputConfig? = nil

  /// Output result indicating where the assets were exported to. For example, a
  /// set of actual Cloud Storage object URIs where the assets are exported to.
  /// The URIs can be different from what [output_config] has specified, as the
  /// service will split the output object into multiple ones once it exceeds a
  /// single Cloud Storage object limit.
  public var outputResult: OutputResult? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `ExportAssetsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportAssetsResponse().with { $0.readTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let readTime = CodingKeys(stringValue: "readTime")
    static let outputConfig = CodingKeys(stringValue: "outputConfig")
    static let outputResult = CodingKeys(stringValue: "outputResult")

    static let _knownKeys: Set<Swift.String> = [
      "readTime",
      "outputConfig",
      "outputResult",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.readTime = try container.decodeIfPresent(GoogleCloudWKT.Timestamp.self, forKey: .readTime)
    self.outputConfig = try container.decodeIfPresent(OutputConfig.self, forKey: .outputConfig)
    self.outputResult = try container.decodeIfPresent(OutputResult.self, forKey: .outputResult)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.readTime, forKey: .readTime)
    try container.encodeIfPresent(self.outputConfig, forKey: .outputConfig)
    try container.encodeIfPresent(self.outputResult, forKey: .outputResult)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.ExportAssetsResponse"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
