// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Export asset request.
public struct ExportAssetsRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The relative name of the root asset. This can only be an
  /// organization number (such as "organizations/123"), a project ID (such as
  /// "projects/my-project-id"), or a project number (such as "projects/12345"),
  /// or a folder number (such as "folders/123").
  public var parent: Swift.String = Swift.String()

  /// Timestamp to take an asset snapshot. This can only be set to a timestamp
  /// between the current time and the current time minus 35 days (inclusive).
  /// If not specified, the current time will be used. Due to delays in resource
  /// data collection and indexing, there is a volatile window during which
  /// running the same query may get different results.
  public var readTime: GoogleCloudWKT.Timestamp? = nil

  /// A list of asset types to take a snapshot for. For example:
  /// "compute.googleapis.com/Disk".
  ///
  /// Regular expressions are also supported. For example:
  ///
  /// * "compute.googleapis.com.*" snapshots resources whose asset type starts
  /// with "compute.googleapis.com".
  /// * ".*Instance" snapshots resources whose asset type ends with "Instance".
  /// * ".*Instance.*" snapshots resources whose asset type contains "Instance".
  ///
  /// See [RE2](https://github.com/google/re2/wiki/Syntax) for all supported
  /// regular expression syntax. If the regular expression does not match any
  /// supported asset type, an INVALID_ARGUMENT error will be returned.
  ///
  /// If specified, only matching assets will be returned, otherwise, it will
  /// snapshot all asset types. See [Introduction to Cloud Asset
  /// Inventory](https://cloud.google.com/asset-inventory/docs/overview)
  /// for all supported asset types.
  public var assetTypes: [Swift.String] = []

  /// Asset content type. If not specified, no content but the asset name will be
  /// returned.
  public var contentType: ContentType = ContentType()

  /// Required. Output configuration indicating where the results will be output
  /// to.
  public var outputConfig: OutputConfig? = nil

  /// A list of relationship types to export, for example:
  /// `INSTANCE_TO_INSTANCEGROUP`. This field should only be specified if
  /// content_type=RELATIONSHIP.
  /// * If specified:
  /// it snapshots specified relationships. It returns an error if
  /// any of the [relationship_types] doesn't belong to the supported
  /// relationship types of the [asset_types] or if any of the [asset_types]
  /// doesn't belong to the source types of the [relationship_types].
  /// * Otherwise:
  /// it snapshots the supported relationships for all [asset_types] or returns
  /// an error if any of the [asset_types] has no relationship support.
  /// An unspecified asset types field means all supported asset_types.
  /// See [Introduction to Cloud Asset
  /// Inventory](https://cloud.google.com/asset-inventory/docs/overview) for all
  /// supported asset types and relationship types.
  public var relationshipTypes: [Swift.String] = []

  /// Initialize a new instance of `ExportAssetsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ExportAssetsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.ExportAssetsRequest"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
