// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleType

/// An asset feed used to export asset updates to a destinations.
/// An asset feed filter controls what updates are exported.
/// The asset feed must be created within a project, organization, or
/// folder. Supported destinations are:
/// Pub/Sub topics.
public struct Feed: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The format will be
  /// projects/{project_number}/feeds/{client-assigned_feed_identifier} or
  /// folders/{folder_number}/feeds/{client-assigned_feed_identifier} or
  /// organizations/{organization_number}/feeds/{client-assigned_feed_identifier}
  ///
  /// The client-assigned feed identifier must be unique within the parent
  /// project/folder/organization.
  public var name: Swift.String = Swift.String()

  /// A list of the full names of the assets to receive updates. You must specify
  /// either or both of asset_names and asset_types. Only asset updates matching
  /// specified asset_names or asset_types are exported to the feed.
  /// Example:
  /// `//compute.googleapis.com/projects/my_project_123/zones/zone1/instances/instance1`.
  /// For a list of the full names for supported asset types, see [Resource
  /// name format](/asset-inventory/docs/resource-name-format).
  public var assetNames: [Swift.String] = []

  /// A list of types of the assets to receive updates. You must specify either
  /// or both of asset_names and asset_types. Only asset updates matching
  /// specified asset_names or asset_types are exported to the feed.
  /// Example: `"compute.googleapis.com/Disk"`
  ///
  /// For a list of all supported asset types, see
  /// [Supported asset types](/asset-inventory/docs/supported-asset-types).
  public var assetTypes: [Swift.String] = []

  /// Asset content type. If not specified, no content but the asset name and
  /// type will be returned.
  public var contentType: ContentType = ContentType()

  /// Required. Feed output configuration defining where the asset updates are
  /// published to.
  public var feedOutputConfig: FeedOutputConfig? = nil

  /// A condition which determines whether an asset update should be published.
  /// If specified, an asset will be returned only when the expression evaluates
  /// to true.
  /// When set, `expression` field in the `Expr` must be a valid [CEL expression]
  /// (https://github.com/google/cel-spec) on a TemporalAsset with name
  /// `temporal_asset`. Example: a Feed with expression ("temporal_asset.deleted
  /// == true") will only publish Asset deletions. Other fields of `Expr` are
  /// optional.
  ///
  /// See our [user
  /// guide](https://cloud.google.com/asset-inventory/docs/monitoring-asset-changes-with-condition)
  /// for detailed instructions.
  public var condition: GoogleType.Expr? = nil

  /// A list of relationship types to output, for example:
  /// `INSTANCE_TO_INSTANCEGROUP`. This field should only be specified if
  /// content_type=RELATIONSHIP.
  /// * If specified:
  /// it outputs specified relationship updates on the [asset_names] or the
  /// [asset_types]. It returns an error if any of the [relationship_types]
  /// doesn't belong to the supported relationship types of the [asset_names] or
  /// [asset_types], or any of the [asset_names] or the [asset_types] doesn't
  /// belong to the source types of the [relationship_types].
  /// * Otherwise:
  /// it outputs the supported relationships of the types of [asset_names] and
  /// [asset_types] or returns an error if any of the [asset_names] or the
  /// [asset_types] has no replationship support.
  /// See [Introduction to Cloud Asset
  /// Inventory](https://cloud.google.com/asset-inventory/docs/overview)
  /// for all supported asset types and relationship types.
  public var relationshipTypes: [Swift.String] = []

  /// Initialize a new instance of `Feed`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Feed().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.Feed"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
