// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Cloud Storage location.
public struct GcsDestination: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required.
  public var objectUri: OneOf_ObjectUri? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `GcsDestination`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsDestination().with { $0.uri = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let uri = CodingKeys(stringValue: "uri")
    static let uriPrefix = CodingKeys(stringValue: "uriPrefix")

    static let _knownKeys: Set<Swift.String> = [
      "uri",
      "uriPrefix",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var objectUri: OneOf_ObjectUri? = nil
    let objectUriCheckAndSet = {
      if objectUri != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'objectUri'"))
      }
      objectUri = $0
    }
    if let uri = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
      try objectUriCheckAndSet(.uri(uri))
    }
    if let uriPrefix = try container.decodeIfPresent(Swift.String.self, forKey: .uriPrefix) {
      try objectUriCheckAndSet(.uriPrefix(uriPrefix))
    }
    self.objectUri = objectUri
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.objectUri {
      switch choice {
      case .uri(let value):
        try container.encode(value, forKey: .uri)
      case .uriPrefix(let value):
        try container.encode(value, forKey: .uriPrefix)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Required.
  public enum OneOf_ObjectUri: Codable, Equatable, Sendable {
    /// The URI of the Cloud Storage object. It's the same URI that is used by
    /// gsutil. Example: "gs://bucket_name/object_name". See [Viewing and
    /// Editing Object
    /// Metadata](https://cloud.google.com/storage/docs/viewing-editing-metadata)
    /// for more information.
    ///
    /// If the specified Cloud Storage object already exists and there is no
    /// [hold](https://cloud.google.com/storage/docs/object-holds), it will be
    /// overwritten with the exported result.
    case uri(Swift.String)
    /// The URI prefix of all generated Cloud Storage objects. Example:
    /// "gs://bucket_name/object_name_prefix". Each object URI is in format:
    /// "gs://bucket_name/object_name_prefix/<asset type>/<shard number> and only
    /// contains assets for that type. <shard number> starts from 0. Example:
    /// "gs://bucket_name/object_name_prefix/compute.googleapis.com/Disk/0" is
    /// the first shard of output objects containing all
    /// compute.googleapis.com/Disk assets. An INVALID_ARGUMENT error will be
    /// returned if file with the same name "gs://bucket_name/object_name_prefix"
    /// already exists.
    case uriPrefix(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.GcsDestination"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
