// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Output configuration for export IAM policy analysis destination.
public struct IamPolicyAnalysisOutputConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// IAM policy analysis export destination.
  public var destination: OneOf_Destination? = nil

  /// Initialize a new instance of `IamPolicyAnalysisOutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IamPolicyAnalysisOutputConfig().with { $0.gcsDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case gcsDestination = "gcsDestination"
    case bigqueryDestination = "bigqueryDestination"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var destination: OneOf_Destination? = nil
    let destinationCheckAndSet = {
      if destination != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destination'"))
      }
      destination = $0
    }
    if let gcsDestination = try container.decodeIfPresent(
      IamPolicyAnalysisOutputConfig.GcsDestination?.self, forKey: .gcsDestination)
    {
      try destinationCheckAndSet(.gcsDestination(gcsDestination))
    }
    if let bigqueryDestination = try container.decodeIfPresent(
      IamPolicyAnalysisOutputConfig.BigQueryDestination?.self, forKey: .bigqueryDestination)
    {
      try destinationCheckAndSet(.bigqueryDestination(bigqueryDestination))
    }
    self.destination = destination
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.destination {
      switch choice {
      case .gcsDestination(let value):
        try container.encode(value, forKey: .gcsDestination)
      case .bigqueryDestination(let value):
        try container.encode(value, forKey: .bigqueryDestination)
      }
    }
  }

  /// A Cloud Storage location.
  public struct GcsDestination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The URI of the Cloud Storage object. It's the same URI that is
    /// used by gsutil. Example: "gs://bucket_name/object_name". See [Viewing and
    /// Editing Object
    /// Metadata](https://cloud.google.com/storage/docs/viewing-editing-metadata)
    /// for more information.
    ///
    /// If the specified Cloud Storage object already exists and there is no
    /// [hold](https://cloud.google.com/storage/docs/object-holds), it will be
    /// overwritten with the analysis result.
    public var uri: Swift.String = Swift.String()

    /// Initialize a new instance of `GcsDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GcsDestination().with { $0.uri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.GcsDestination"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A BigQuery destination.
  public struct BigQueryDestination: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The BigQuery dataset in format
    /// "projects/projectId/datasets/datasetId", to which the analysis results
    /// should be exported. If this dataset does not exist, the export call will
    /// return an INVALID_ARGUMENT error.
    public var dataset: Swift.String = Swift.String()

    /// Required. The prefix of the BigQuery tables to which the analysis results
    /// will be written. Tables will be created based on this table_prefix if not
    /// exist:
    /// * <table_prefix>_analysis table will contain export operation's metadata.
    /// * <table_prefix>_analysis_result will contain all the
    ///   [IamPolicyAnalysisResult][google.cloud.asset.v1.IamPolicyAnalysisResult].
    /// When [partition_key] is specified, both tables will be partitioned based
    /// on the [partition_key].
    ///
    /// [google.cloud.asset.v1.IamPolicyAnalysisResult]: <doc:IamPolicyAnalysisResult>
    public var tablePrefix: Swift.String = Swift.String()

    /// The partition key for BigQuery partitioned table.
    public var partitionKey: IamPolicyAnalysisOutputConfig.BigQueryDestination.PartitionKey =
      IamPolicyAnalysisOutputConfig.BigQueryDestination.PartitionKey()

    /// Optional. Specifies the action that occurs if the destination table or
    /// partition already exists. The following values are supported:
    ///
    /// * WRITE_TRUNCATE: If the table or partition already exists, BigQuery
    /// overwrites the entire table or all the partitions data.
    /// * WRITE_APPEND: If the table or partition already exists, BigQuery
    /// appends the data to the table or the latest partition.
    /// * WRITE_EMPTY: If the table already exists and contains data, an error is
    /// returned.
    ///
    /// The default value is WRITE_APPEND. Each action is atomic and only occurs
    /// if BigQuery is able to complete the job successfully. Details are at
    /// https://cloud.google.com/bigquery/docs/loading-data-local#appending_to_or_overwriting_a_table_using_a_local_file.
    public var writeDisposition: Swift.String = Swift.String()

    /// Initialize a new instance of `BigQueryDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BigQueryDestination().with { $0.dataset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// This enum determines the partition key column for the bigquery tables.
    /// Partitioning can improve query performance and reduce query cost by
    /// filtering partitions. Refer to
    /// https://cloud.google.com/bigquery/docs/partitioned-tables for details.
    public enum PartitionKey: Codable, Equatable, Sendable {
      /// Unspecified partition key. Tables won't be partitioned using this
      /// option.
      case unspecified
      /// The time when the request is received. If specified as partition key,
      /// the result table(s) is partitioned by the RequestTime column, an
      /// additional timestamp column representing when the request was received.
      case requestTime
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .requestTime: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "PARTITION_KEY_UNSPECIFIED"
        case .requestTime: return "REQUEST_TIME"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PartitionKey/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "PARTITION_KEY_UNSPECIFIED": self = .unspecified
        case "REQUEST_TIME": self = .requestTime
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PartitionKey/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .requestTime
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .requestTime: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisOutputConfig.BigQueryDestination"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// IAM policy analysis export destination.
  public enum OneOf_Destination: Codable, Equatable, Sendable {
    /// Destination on Cloud Storage.
    indirect case gcsDestination(IamPolicyAnalysisOutputConfig.GcsDestination?)
    /// Destination on BigQuery.
    indirect case bigqueryDestination(IamPolicyAnalysisOutputConfig.BigQueryDestination?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisOutputConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
