// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// IAM policy analysis query message.
public struct IamPolicyAnalysisQuery: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The relative name of the root asset. Only resources and IAM
  /// policies within the scope will be analyzed.
  ///
  /// This can only be an organization number (such as "organizations/123"), a
  /// folder number (such as "folders/123"), a project ID (such as
  /// "projects/my-project-id"), or a project number (such as "projects/12345").
  ///
  /// To know how to get organization ID, visit [here
  /// ](https://cloud.google.com/resource-manager/docs/creating-managing-organization#retrieving_your_organization_id).
  ///
  /// To know how to get folder or project ID, visit [here
  /// ](https://cloud.google.com/resource-manager/docs/creating-managing-folders#viewing_or_listing_folders_and_projects).
  public var scope: Swift.String = Swift.String()

  /// Optional. Specifies a resource for analysis.
  public var resourceSelector: IamPolicyAnalysisQuery.ResourceSelector? = nil

  /// Optional. Specifies an identity for analysis.
  public var identitySelector: IamPolicyAnalysisQuery.IdentitySelector? = nil

  /// Optional. Specifies roles or permissions for analysis. This is optional.
  public var accessSelector: IamPolicyAnalysisQuery.AccessSelector? = nil

  /// Optional. The query options.
  public var options: IamPolicyAnalysisQuery.Options? = nil

  /// Optional. The hypothetical context for IAM conditions evaluation.
  public var conditionContext: IamPolicyAnalysisQuery.ConditionContext? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `IamPolicyAnalysisQuery`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = IamPolicyAnalysisQuery().with { $0.scope = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let scope = CodingKeys(stringValue: "scope")
    static let resourceSelector = CodingKeys(stringValue: "resourceSelector")
    static let identitySelector = CodingKeys(stringValue: "identitySelector")
    static let accessSelector = CodingKeys(stringValue: "accessSelector")
    static let options = CodingKeys(stringValue: "options")
    static let conditionContext = CodingKeys(stringValue: "conditionContext")

    static let _knownKeys: Set<Swift.String> = [
      "scope",
      "resourceSelector",
      "identitySelector",
      "accessSelector",
      "options",
      "conditionContext",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .scope) {
      self.scope = value
    }
    self.resourceSelector = try container.decodeIfPresent(
      IamPolicyAnalysisQuery.ResourceSelector.self, forKey: .resourceSelector)
    self.identitySelector = try container.decodeIfPresent(
      IamPolicyAnalysisQuery.IdentitySelector.self, forKey: .identitySelector)
    self.accessSelector = try container.decodeIfPresent(
      IamPolicyAnalysisQuery.AccessSelector.self, forKey: .accessSelector)
    self.options = try container.decodeIfPresent(
      IamPolicyAnalysisQuery.Options.self, forKey: .options)
    self.conditionContext = try container.decodeIfPresent(
      IamPolicyAnalysisQuery.ConditionContext.self, forKey: .conditionContext)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.scope, forKey: .scope)
    try container.encodeIfPresent(self.resourceSelector, forKey: .resourceSelector)
    try container.encodeIfPresent(self.identitySelector, forKey: .identitySelector)
    try container.encodeIfPresent(self.accessSelector, forKey: .accessSelector)
    try container.encodeIfPresent(self.options, forKey: .options)
    try container.encodeIfPresent(self.conditionContext, forKey: .conditionContext)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Specifies the resource to analyze for access policies, which may be set
  /// directly on the resource, or on ancestors such as organizations, folders or
  /// projects.
  public struct ResourceSelector: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The [full resource name]
    /// (https://cloud.google.com/asset-inventory/docs/resource-name-format)
    /// of a resource of [supported resource
    /// types](https://cloud.google.com/asset-inventory/docs/supported-asset-types#analyzable_asset_types).
    public var fullResourceName: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ResourceSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ResourceSelector().with { $0.fullResourceName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let fullResourceName = CodingKeys(stringValue: "fullResourceName")

      static let _knownKeys: Set<Swift.String> = [
        "fullResourceName"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .fullResourceName) {
        self.fullResourceName = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.fullResourceName, forKey: .fullResourceName)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisQuery.ResourceSelector"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Specifies an identity for which to determine resource access, based on
  /// roles assigned either directly to them or to the groups they belong to,
  /// directly or indirectly.
  public struct IdentitySelector: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The identity appear in the form of principals in
    /// [IAM policy
    /// binding](https://cloud.google.com/iam/reference/rest/v1/Binding).
    ///
    /// The examples of supported forms are:
    /// "user:mike@example.com",
    /// "group:admins@example.com",
    /// "domain:google.com",
    /// "serviceAccount:my-project-id@appspot.gserviceaccount.com".
    ///
    /// Notice that wildcard characters (such as * and ?) are not supported.
    /// You must give a specific identity.
    public var identity: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IdentitySelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IdentitySelector().with { $0.identity = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let identity = CodingKeys(stringValue: "identity")

      static let _knownKeys: Set<Swift.String> = [
        "identity"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .identity) {
        self.identity = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.identity, forKey: .identity)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisQuery.IdentitySelector"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Specifies roles and/or permissions to analyze, to determine both the
  /// identities possessing them and the resources they control. If multiple
  /// values are specified, results will include roles or permissions matching
  /// any of them. The total number of roles and permissions should be equal or
  /// less than 10.
  public struct AccessSelector: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The roles to appear in result.
    public var roles: [Swift.String] = []

    /// Optional. The permissions to appear in result.
    public var permissions: [Swift.String] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AccessSelector`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AccessSelector().with { $0.roles = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let roles = CodingKeys(stringValue: "roles")
      static let permissions = CodingKeys(stringValue: "permissions")

      static let _knownKeys: Set<Swift.String> = [
        "roles",
        "permissions",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .roles) {
        self.roles = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .permissions) {
        self.permissions = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.roles, forKey: .roles)
      try container.encode(self.permissions, forKey: .permissions)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisQuery.AccessSelector"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Contains query options.
  public struct Options: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. If true, the identities section of the result will expand any
    /// Google groups appearing in an IAM policy binding.
    ///
    /// If
    /// [IamPolicyAnalysisQuery.identity_selector][google.cloud.asset.v1.IamPolicyAnalysisQuery.identity_selector]
    /// is specified, the identity in the result will be determined by the
    /// selector, and this flag is not allowed to set.
    ///
    /// If true, the default max expansion per group is 1000 for
    /// AssetService.AnalyzeIamPolicy][].
    ///
    /// Default is false.
    ///
    /// [google.cloud.asset.v1.IamPolicyAnalysisQuery.identity_selector]: <doc:IamPolicyAnalysisQuery/identitySelector>
    public var expandGroups: Swift.Bool = Swift.Bool()

    /// Optional. If true, the access section of result will expand any roles
    /// appearing in IAM policy bindings to include their permissions.
    ///
    /// If
    /// [IamPolicyAnalysisQuery.access_selector][google.cloud.asset.v1.IamPolicyAnalysisQuery.access_selector]
    /// is specified, the access section of the result will be determined by the
    /// selector, and this flag is not allowed to set.
    ///
    /// Default is false.
    ///
    /// [google.cloud.asset.v1.IamPolicyAnalysisQuery.access_selector]: <doc:IamPolicyAnalysisQuery/accessSelector>
    public var expandRoles: Swift.Bool = Swift.Bool()

    /// Optional. If true and
    /// [IamPolicyAnalysisQuery.resource_selector][google.cloud.asset.v1.IamPolicyAnalysisQuery.resource_selector]
    /// is not specified, the resource section of the result will expand any
    /// resource attached to an IAM policy to include resources lower in the
    /// resource hierarchy.
    ///
    /// For example, if the request analyzes for which resources user A has
    /// permission P, and the results include an IAM policy with P on a Google
    /// Cloud folder, the results will also include resources in that folder with
    /// permission P.
    ///
    /// If true and
    /// [IamPolicyAnalysisQuery.resource_selector][google.cloud.asset.v1.IamPolicyAnalysisQuery.resource_selector]
    /// is specified, the resource section of the result will expand the
    /// specified resource to include resources lower in the resource hierarchy.
    /// Only project or lower resources are supported. Folder and organization
    /// resources cannot be used together with this option.
    ///
    /// For example, if the request analyzes for which users have permission P on
    /// a Google Cloud project with this option enabled, the results will include
    /// all users who have permission P on that project or any lower resource.
    ///
    /// If true, the default max expansion per resource is 1000 for
    /// AssetService.AnalyzeIamPolicy][] and 100000 for
    /// AssetService.AnalyzeIamPolicyLongrunning][].
    ///
    /// Default is false.
    ///
    /// [google.cloud.asset.v1.IamPolicyAnalysisQuery.resource_selector]: <doc:IamPolicyAnalysisQuery/resourceSelector>
    public var expandResources: Swift.Bool = Swift.Bool()

    /// Optional. If true, the result will output the relevant parent/child
    /// relationships between resources. Default is false.
    public var outputResourceEdges: Swift.Bool = Swift.Bool()

    /// Optional. If true, the result will output the relevant membership
    /// relationships between groups and other groups, and between groups and
    /// principals. Default is false.
    public var outputGroupEdges: Swift.Bool = Swift.Bool()

    /// Optional. If true, the response will include access analysis from
    /// identities to resources via service account impersonation. This is a very
    /// expensive operation, because many derived queries will be executed. We
    /// highly recommend you use
    /// [AssetService.AnalyzeIamPolicyLongrunning][google.cloud.asset.v1.AssetService.AnalyzeIamPolicyLongrunning]
    /// RPC instead.
    ///
    /// For example, if the request analyzes for which resources user A has
    /// permission P, and there's an IAM policy states user A has
    /// iam.serviceAccounts.getAccessToken permission to a service account SA,
    /// and there's another IAM policy states service account SA has permission P
    /// to a Google Cloud folder F, then user A potentially has access to the
    /// Google Cloud folder F. And those advanced analysis results will be
    /// included in
    /// [AnalyzeIamPolicyResponse.service_account_impersonation_analysis][google.cloud.asset.v1.AnalyzeIamPolicyResponse.service_account_impersonation_analysis].
    ///
    /// Another example, if the request analyzes for who has
    /// permission P to a Google Cloud folder F, and there's an IAM policy states
    /// user A has iam.serviceAccounts.actAs permission to a service account SA,
    /// and there's another IAM policy states service account SA has permission P
    /// to the Google Cloud folder F, then user A potentially has access to the
    /// Google Cloud folder F. And those advanced analysis results will be
    /// included in
    /// [AnalyzeIamPolicyResponse.service_account_impersonation_analysis][google.cloud.asset.v1.AnalyzeIamPolicyResponse.service_account_impersonation_analysis].
    ///
    /// Only the following permissions are considered in this analysis:
    ///
    /// * `iam.serviceAccounts.actAs`
    /// * `iam.serviceAccounts.signBlob`
    /// * `iam.serviceAccounts.signJwt`
    /// * `iam.serviceAccounts.getAccessToken`
    /// * `iam.serviceAccounts.getOpenIdToken`
    /// * `iam.serviceAccounts.implicitDelegation`
    ///
    /// Default is false.
    ///
    /// [google.cloud.asset.v1.AnalyzeIamPolicyResponse.service_account_impersonation_analysis]: <doc:AnalyzeIamPolicyResponse/serviceAccountImpersonationAnalysis>
    /// [google.cloud.asset.v1.AssetService.AnalyzeIamPolicyLongrunning]: <doc:AssetServiceClient/analyzeIamPolicyLongrunning(request:options:)>
    public var analyzeServiceAccountImpersonation: Swift.Bool = Swift.Bool()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Options`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Options().with { $0.expandGroups = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let expandGroups = CodingKeys(stringValue: "expandGroups")
      static let expandRoles = CodingKeys(stringValue: "expandRoles")
      static let expandResources = CodingKeys(stringValue: "expandResources")
      static let outputResourceEdges = CodingKeys(stringValue: "outputResourceEdges")
      static let outputGroupEdges = CodingKeys(stringValue: "outputGroupEdges")
      static let analyzeServiceAccountImpersonation = CodingKeys(
        stringValue: "analyzeServiceAccountImpersonation")

      static let _knownKeys: Set<Swift.String> = [
        "expandGroups",
        "expandRoles",
        "expandResources",
        "outputResourceEdges",
        "outputGroupEdges",
        "analyzeServiceAccountImpersonation",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .expandGroups) {
        self.expandGroups = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .expandRoles) {
        self.expandRoles = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .expandResources) {
        self.expandResources = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .outputResourceEdges) {
        self.outputResourceEdges = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .outputGroupEdges) {
        self.outputGroupEdges = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Bool.self, forKey: .analyzeServiceAccountImpersonation)
      {
        self.analyzeServiceAccountImpersonation = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.expandGroups, forKey: .expandGroups)
      try container.encode(self.expandRoles, forKey: .expandRoles)
      try container.encode(self.expandResources, forKey: .expandResources)
      try container.encode(self.outputResourceEdges, forKey: .outputResourceEdges)
      try container.encode(self.outputGroupEdges, forKey: .outputGroupEdges)
      try container.encode(
        self.analyzeServiceAccountImpersonation, forKey: .analyzeServiceAccountImpersonation)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisQuery.Options"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The IAM conditions context.
  public struct ConditionContext: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The IAM conditions time context.
    public var timeContext: OneOf_TimeContext? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConditionContext`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConditionContext().with { $0.accessTime = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let accessTime = CodingKeys(stringValue: "accessTime")

      static let _knownKeys: Set<Swift.String> = [
        "accessTime"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var timeContext: OneOf_TimeContext? = nil
      let timeContextCheckAndSet = {
        if timeContext != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'timeContext'"))
        }
        timeContext = $0
      }
      if let accessTime = try container.decodeIfPresent(
        GoogleWKT.Timestamp?.self, forKey: .accessTime)
      {
        try timeContextCheckAndSet(.accessTime(accessTime))
      }
      self.timeContext = timeContext
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.timeContext {
        switch choice {
        case .accessTime(let value):
          try container.encode(value, forKey: .accessTime)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The IAM conditions time context.
    public enum OneOf_TimeContext: Codable, Equatable, Sendable {
      /// The hypothetical access timestamp to evaluate IAM conditions. Note that
      /// this value must not be earlier than the current time; otherwise, an
      /// INVALID_ARGUMENT error will be returned.
      indirect case accessTime(GoogleWKT.Timestamp?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisQuery.ConditionContext"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.IamPolicyAnalysisQuery"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
