// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt
import GoogleRpc

/// A message to group the analysis information.
public struct MoveAnalysis: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The user friendly display name of the analysis. E.g. IAM, organization
  /// policy etc.
  public var displayName: Swift.String = Swift.String()

  public var result: OneOf_Result? = nil

  /// Initialize a new instance of `MoveAnalysis`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MoveAnalysis().with { $0.displayName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case displayName = "displayName"
    case analysis = "analysis"
    case error = "error"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.displayName = try container.decode(Swift.String.self, forKey: .displayName)

    var result: OneOf_Result? = nil
    let resultCheckAndSet = {
      if result != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'result'"))
      }
      result = $0
    }
    if let analysis = try container.decodeIfPresent(MoveAnalysisResult?.self, forKey: .analysis) {
      try resultCheckAndSet(.analysis(analysis))
    }
    if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
      try resultCheckAndSet(.error(error))
    }
    self.result = result
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.displayName, forKey: .displayName)

    if let choice = self.result {
      switch choice {
      case .analysis(let value):
        try container.encode(value, forKey: .analysis)
      case .error(let value):
        try container.encode(value, forKey: .error)
      }
    }
  }

  public enum OneOf_Result: Codable, Equatable, Sendable {
    /// Analysis result of moving the target resource.
    indirect case analysis(MoveAnalysisResult?)
    /// Description of error encountered when performing the analysis.
    indirect case error(GoogleRpc.Status?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.MoveAnalysis"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
