// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Specifications of BigQuery partitioned table as export destination.
public struct PartitionSpec: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// The partition key for BigQuery partitioned table.
  public var partitionKey: PartitionSpec.PartitionKey = PartitionSpec.PartitionKey()

  /// Initialize a new instance of `PartitionSpec`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PartitionSpec().with { $0.partitionKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// This enum is used to determine the partition key column when exporting
  /// assets to BigQuery partitioned table(s). Note that, if the partition key is
  /// a timestamp column, the actual partition is based on its date value
  /// (expressed in UTC. see details in
  /// https://cloud.google.com/bigquery/docs/partitioned-tables#date_timestamp_partitioned_tables).
  public enum PartitionKey: Codable, Equatable, Sendable {
    /// Unspecified partition key. If used, it means using non-partitioned table.
    case unspecified
    /// The time when the snapshot is taken. If specified as partition key, the
    /// result table(s) is partitioned by the additional timestamp column,
    /// readTime. If [read_time] in ExportAssetsRequest is specified, the
    /// readTime column's value will be the same as it. Otherwise, its value will
    /// be the current time that is used to take the snapshot.
    case readTime
    /// The time when the request is received and started to be processed. If
    /// specified as partition key, the result table(s) is partitioned by the
    /// requestTime column, an additional timestamp column representing when the
    /// request was received.
    case requestTime
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .readTime: return 1
      case .requestTime: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "PARTITION_KEY_UNSPECIFIED"
      case .readTime: return "READ_TIME"
      case .requestTime: return "REQUEST_TIME"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:PartitionKey/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "PARTITION_KEY_UNSPECIFIED": self = .unspecified
      case "READ_TIME": self = .readTime
      case "REQUEST_TIME": self = .requestTime
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:PartitionKey/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .readTime
      case 2: self = .requestTime
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .readTime: return try container.encode(1)
      case .requestTime: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.PartitionSpec"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
