// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleWKT

/// QueryAssets response.
public struct QueryAssetsResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Reference to a query job.
  public var jobReference: Swift.String = Swift.String()

  /// The query response, which can be either an `error` or a valid `response`.
  ///
  /// If `done` == `false` and the query result is being saved in an output, the
  /// output_config field will be set.
  /// If `done` == `true`, exactly one of
  /// `error`, `query_result` or `output_config` will be set.
  /// [done] is unset unless the [QueryAssetsResponse] contains a
  /// [QueryAssetsResponse.job_reference].
  public var done: Swift.Bool = Swift.Bool()

  public var response: OneOf_Response? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QueryAssetsResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryAssetsResponse().with { $0.jobReference = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let jobReference = CodingKeys(stringValue: "jobReference")
    static let done = CodingKeys(stringValue: "done")
    static let error = CodingKeys(stringValue: "error")
    static let queryResult = CodingKeys(stringValue: "queryResult")
    static let outputConfig = CodingKeys(stringValue: "outputConfig")

    static let _knownKeys: Set<Swift.String> = [
      "jobReference",
      "done",
      "error",
      "queryResult",
      "outputConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .jobReference) {
      self.jobReference = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .done) {
      self.done = value
    }

    var response: OneOf_Response? = nil
    let responseCheckAndSet = {
      if response != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'response'"))
      }
      response = $0
    }
    if let error = try container.decodeIfPresent(GoogleRpc.Status?.self, forKey: .error) {
      try responseCheckAndSet(.error(error))
    }
    if let queryResult = try container.decodeIfPresent(QueryResult?.self, forKey: .queryResult) {
      try responseCheckAndSet(.queryResult(queryResult))
    }
    if let outputConfig = try container.decodeIfPresent(
      QueryAssetsOutputConfig?.self, forKey: .outputConfig)
    {
      try responseCheckAndSet(.outputConfig(outputConfig))
    }
    self.response = response
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.jobReference, forKey: .jobReference)
    try container.encode(self.done, forKey: .done)

    if let choice = self.response {
      switch choice {
      case .error(let value):
        try container.encode(value, forKey: .error)
      case .queryResult(let value):
        try container.encode(value, forKey: .queryResult)
      case .outputConfig(let value):
        try container.encode(value, forKey: .outputConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_Response: Codable, Equatable, Sendable {
    /// Error status.
    indirect case error(GoogleRpc.Status?)
    /// Result of the query.
    indirect case queryResult(QueryResult?)
    /// Output configuration, which indicates that instead of being returned in
    /// an API response on the fly, the query result will be saved in a specific
    /// output.
    indirect case outputConfig(QueryAssetsOutputConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.QueryAssetsResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
