// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Output configuration query assets.
public struct QueryAssetsOutputConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// BigQuery destination where the query results will be saved.
  public var bigqueryDestination: QueryAssetsOutputConfig.BigQueryDestination? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `QueryAssetsOutputConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryAssetsOutputConfig().with { $0.bigqueryDestination = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let bigqueryDestination = CodingKeys(stringValue: "bigqueryDestination")

    static let _knownKeys: Set<Swift.String> = [
      "bigqueryDestination"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.bigqueryDestination = try container.decodeIfPresent(
      QueryAssetsOutputConfig.BigQueryDestination.self, forKey: .bigqueryDestination)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.bigqueryDestination, forKey: .bigqueryDestination)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// BigQuery destination.
  public struct BigQueryDestination: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The BigQuery dataset where the query results will be saved. It
    /// has the format of "projects/{projectId}/datasets/{datasetId}".
    public var dataset: Swift.String = Swift.String()

    /// Required. The BigQuery table where the query results will be saved. If
    /// this table does not exist, a new table with the given name will be
    /// created.
    public var table: Swift.String = Swift.String()

    /// Specifies the action that occurs if the destination table or partition
    /// already exists. The following values are supported:
    ///
    /// * WRITE_TRUNCATE: If the table or partition already exists, BigQuery
    /// overwrites the entire table or all the partitions data.
    /// * WRITE_APPEND: If the table or partition already exists, BigQuery
    /// appends the data to the table or the latest partition.
    /// * WRITE_EMPTY: If the table already exists and contains data, a
    /// 'duplicate' error is returned in the job result.
    ///
    /// The default value is WRITE_EMPTY.
    public var writeDisposition: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BigQueryDestination`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BigQueryDestination().with { $0.dataset = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let dataset = CodingKeys(stringValue: "dataset")
      static let table = CodingKeys(stringValue: "table")
      static let writeDisposition = CodingKeys(stringValue: "writeDisposition")

      static let _knownKeys: Set<Swift.String> = [
        "dataset",
        "table",
        "writeDisposition",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .dataset) {
        self.dataset = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .table) {
        self.table = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .writeDisposition) {
        self.writeDisposition = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.dataset, forKey: .dataset)
      try container.encode(self.table, forKey: .table)
      try container.encode(self.writeDisposition, forKey: .writeDisposition)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.QueryAssetsOutputConfig.BigQueryDestination"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.QueryAssetsOutputConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
