// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// QueryAssets request.
public struct QueryAssetsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The relative name of the root asset. This can only be an
  /// organization number (such as "organizations/123"), a project ID (such as
  /// "projects/my-project-id"), or a project number (such as "projects/12345"),
  /// or a folder number (such as "folders/123").
  ///
  /// Only assets belonging to the `parent` will be returned.
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of rows to return in the results. Responses
  /// are limited to 10 MB and 1000 rows.
  ///
  /// By default, the maximum row count is 1000. When the byte or row count limit
  /// is reached, the rest of the query results will be paginated.
  ///
  /// The field will be ignored when [output_config] is specified.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token received from previous `QueryAssets`.
  ///
  /// The field will be ignored when [output_config] is specified.
  public var pageToken: Swift.String = Swift.String()

  /// Optional. Specifies the maximum amount of time that the client is willing
  /// to wait for the query to complete. By default, this limit is 5 min for the
  /// first query, and 1 minute for the following queries. If the query is
  /// complete, the `done` field in the `QueryAssetsResponse` is true, otherwise
  /// false.
  ///
  /// Like BigQuery [jobs.query
  /// API](https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query#queryrequest)
  /// The call is not guaranteed to wait for the specified timeout; it typically
  /// returns after around 200 seconds (200,000 milliseconds), even if the query
  /// is not complete.
  ///
  /// The field will be ignored when [output_config] is specified.
  public var timeout: GoogleCloudWkt.Duration? = nil

  /// Optional. Destination where the query results will be saved.
  ///
  /// When this field is specified, the query results won't be saved in the
  /// [QueryAssetsResponse.query_result]. Instead
  /// [QueryAssetsResponse.output_config] will be set.
  ///
  /// Meanwhile, [QueryAssetsResponse.job_reference] will be set and can be used
  /// to check the status of the query job when passed to a following
  /// [QueryAssets] API call.
  public var outputConfig: QueryAssetsOutputConfig? = nil

  public var query: OneOf_Query? = nil

  /// Specifies what time period or point in time to query asset metadata at.
  /// * unset - query asset metadata as it is right now
  /// * [read_time_window] - query asset metadata as it was at any point in time
  /// between [start_time] and [end_time].
  /// * [read_time] - query asset metadata as it was at that point in time.
  /// If data for the timestamp/date range selected does not exist,
  /// it will simply return a valid response with no rows.
  public var time: OneOf_Time? = nil

  /// Initialize a new instance of `QueryAssetsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryAssetsRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case parent = "parent"
    case statement = "statement"
    case jobReference = "jobReference"
    case pageSize = "pageSize"
    case pageToken = "pageToken"
    case timeout = "timeout"
    case readTimeWindow = "readTimeWindow"
    case readTime = "readTime"
    case outputConfig = "outputConfig"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.parent = try container.decode(Swift.String.self, forKey: .parent)
    self.pageSize = try container.decode(Swift.Int32.self, forKey: .pageSize)
    self.pageToken = try container.decode(Swift.String.self, forKey: .pageToken)
    self.timeout = try container.decodeIfPresent(GoogleCloudWkt.Duration.self, forKey: .timeout)
    self.outputConfig = try container.decodeIfPresent(
      QueryAssetsOutputConfig.self, forKey: .outputConfig)

    var query: OneOf_Query? = nil
    let queryCheckAndSet = {
      if query != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'query'"))
      }
      query = $0
    }
    if let statement = try container.decodeIfPresent(Swift.String.self, forKey: .statement) {
      try queryCheckAndSet(.statement(statement))
    }
    if let jobReference = try container.decodeIfPresent(Swift.String.self, forKey: .jobReference) {
      try queryCheckAndSet(.jobReference(jobReference))
    }
    self.query = query

    var time: OneOf_Time? = nil
    let timeCheckAndSet = {
      if time != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'time'"
          ))
      }
      time = $0
    }
    if let readTimeWindow = try container.decodeIfPresent(TimeWindow?.self, forKey: .readTimeWindow)
    {
      try timeCheckAndSet(.readTimeWindow(readTimeWindow))
    }
    if let readTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp?.self, forKey: .readTime)
    {
      try timeCheckAndSet(.readTime(readTime))
    }
    self.time = time
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.pageSize, forKey: .pageSize)
    try container.encode(self.pageToken, forKey: .pageToken)
    try container.encode(self.timeout, forKey: .timeout)
    try container.encode(self.outputConfig, forKey: .outputConfig)

    if let choice = self.query {
      switch choice {
      case .statement(let value):
        try container.encode(value, forKey: .statement)
      case .jobReference(let value):
        try container.encode(value, forKey: .jobReference)
      }
    }

    if let choice = self.time {
      switch choice {
      case .readTimeWindow(let value):
        try container.encode(value, forKey: .readTimeWindow)
      case .readTime(let value):
        try container.encode(value, forKey: .readTime)
      }
    }
  }

  public enum OneOf_Query: Codable, Equatable, Sendable {
    /// Optional. A SQL statement that's compatible with [BigQuery
    /// SQL](https://cloud.google.com/bigquery/docs/introduction-sql).
    case statement(Swift.String)
    /// Optional. Reference to the query job, which is from the
    /// `QueryAssetsResponse` of previous `QueryAssets` call.
    case jobReference(Swift.String)
  }

  /// Specifies what time period or point in time to query asset metadata at.
  /// * unset - query asset metadata as it is right now
  /// * [read_time_window] - query asset metadata as it was at any point in time
  /// between [start_time] and [end_time].
  /// * [read_time] - query asset metadata as it was at that point in time.
  /// If data for the timestamp/date range selected does not exist,
  /// it will simply return a valid response with no rows.
  public enum OneOf_Time: Codable, Equatable, Sendable {
    /// Optional. [start_time] is required. [start_time] must be less than
    /// [end_time] Defaults [end_time] to now if [start_time] is set and
    /// [end_time] isn't. Maximum permitted time range is 7 days.
    indirect case readTimeWindow(TimeWindow?)
    /// Optional. Queries cloud assets as they appeared at the specified point in
    /// time.
    indirect case readTime(GoogleCloudWkt.Timestamp?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.QueryAssetsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
