// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Execution results of the query.
///
/// The result is formatted as rows represented by BigQuery compatible [schema].
/// When pagination is necessary, it will contains the page token to retrieve
/// the results of following pages.
public struct QueryResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Each row hold a query result in the format of `Struct`.
  public var rows: [GoogleCloudWKT.Struct] = []

  /// Describes the format of the [rows].
  public var schema: TableSchema? = nil

  /// Token to retrieve the next page of the results.
  public var nextPageToken: Swift.String = Swift.String()

  /// Total rows of the whole query results.
  public var totalRows: Swift.Int64 = Swift.Int64()

  /// Initialize a new instance of `QueryResult`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = QueryResult().with { $0.rows = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.QueryResult"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
