// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// DEPRECATED. This message only presents for the purpose of
/// backward-compatibility. The server will never populate this message in
/// responses.
/// The relationship attributes which include  `type`, `source_resource_type`,
/// `target_resource_type` and `action`.
@available(*, deprecated)
public struct RelationshipAttributes: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The unique identifier of the relationship type. Example:
  /// `INSTANCE_TO_INSTANCEGROUP`
  public var type: Swift.String = Swift.String()

  /// The source asset type. Example: `compute.googleapis.com/Instance`
  public var sourceResourceType: Swift.String = Swift.String()

  /// The target asset type. Example: `compute.googleapis.com/Disk`
  public var targetResourceType: Swift.String = Swift.String()

  /// The detail of the relationship, e.g. `contains`, `attaches`
  public var action: Swift.String = Swift.String()

  /// Initialize a new instance of `RelationshipAttributes`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = RelationshipAttributes().with { $0.type = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.RelationshipAttributes"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
