// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A saved query which can be shared with others or used later.
public struct SavedQuery: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The resource name of the saved query. The format must be:
  ///
  /// * projects/project_number/savedQueries/saved_query_id
  /// * folders/folder_number/savedQueries/saved_query_id
  /// * organizations/organization_number/savedQueries/saved_query_id
  public var name: Swift.String = Swift.String()

  /// The description of this saved query. This value should be fewer than 255
  /// characters.
  public var description: Swift.String = Swift.String()

  /// Output only. The create time of this saved query.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The account's email address who has created this saved query.
  public var creator: Swift.String = Swift.String()

  /// Output only. The last update time of this saved query.
  public var lastUpdateTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The account's email address who has updated this saved query
  /// most recently.
  public var lastUpdater: Swift.String = Swift.String()

  /// Labels applied on the resource.
  /// This value should not contain more than 10 entries. The key and value of
  /// each entry must be non-empty and fewer than 64 characters.
  public var labels: [Swift.String: Swift.String] = [:]

  /// The query content.
  public var content: SavedQuery.QueryContent? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SavedQuery`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SavedQuery().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let description = CodingKeys(stringValue: "description")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let creator = CodingKeys(stringValue: "creator")
    static let lastUpdateTime = CodingKeys(stringValue: "lastUpdateTime")
    static let lastUpdater = CodingKeys(stringValue: "lastUpdater")
    static let labels = CodingKeys(stringValue: "labels")
    static let content = CodingKeys(stringValue: "content")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "description",
      "createTime",
      "creator",
      "lastUpdateTime",
      "lastUpdater",
      "labels",
      "content",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
      self.description = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .creator) {
      self.creator = value
    }
    self.lastUpdateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .lastUpdateTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .lastUpdater) {
      self.lastUpdater = value
    }
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.content = try container.decodeIfPresent(SavedQuery.QueryContent.self, forKey: .content)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.description, forKey: .description)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encode(self.creator, forKey: .creator)
    try container.encodeIfPresent(self.lastUpdateTime, forKey: .lastUpdateTime)
    try container.encode(self.lastUpdater, forKey: .lastUpdater)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.content, forKey: .content)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The query content.
  public struct QueryContent: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var queryContent: QueryContentOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `QueryContent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = QueryContent().with { $0.iamPolicyAnalysisQuery = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let iamPolicyAnalysisQuery = CodingKeys(stringValue: "iamPolicyAnalysisQuery")

      static let _knownKeys: Set<Swift.String> = [
        "iamPolicyAnalysisQuery"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var queryContent: QueryContentOneOf? = nil
      let queryContentCheckAndSet = {
        if queryContent != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'queryContent'"))
        }
        queryContent = $0
      }
      if let iamPolicyAnalysisQuery = try container.decodeIfPresent(
        IamPolicyAnalysisQuery?.self, forKey: .iamPolicyAnalysisQuery)
      {
        try queryContentCheckAndSet(.iamPolicyAnalysisQuery(iamPolicyAnalysisQuery))
      }
      self.queryContent = queryContent
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.queryContent {
        switch choice {
        case .iamPolicyAnalysisQuery(let value):
          try container.encode(value, forKey: .iamPolicyAnalysisQuery)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public enum QueryContentOneOf: Codable, Equatable, Sendable {
      /// An IAM Policy Analysis query, which could be used in
      /// the
      /// [AssetService.AnalyzeIamPolicy][google.cloud.asset.v1.AssetService.AnalyzeIamPolicy]
      /// RPC or the
      /// [AssetService.AnalyzeIamPolicyLongrunning][google.cloud.asset.v1.AssetService.AnalyzeIamPolicyLongrunning]
      /// RPC.
      ///
      /// [google.cloud.asset.v1.AssetService.AnalyzeIamPolicy]: <doc:AssetServiceClient/analyzeIamPolicy(request:options:)>
      /// [google.cloud.asset.v1.AssetService.AnalyzeIamPolicyLongrunning]: <doc:AssetServiceClient/analyzeIamPolicyLongrunning(request:options:)>
      indirect case iamPolicyAnalysisQuery(IamPolicyAnalysisQuery?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.asset.v1.SavedQuery.QueryContent"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.SavedQuery"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
