// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A field in TableSchema.
public struct TableFieldSchema: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The field name. The name must contain only letters (a-z, A-Z),
  /// numbers (0-9), or underscores (_), and must start with a letter or
  /// underscore. The maximum length is 128 characters.
  public var field: Swift.String = Swift.String()

  /// The field data type. Possible values include
  /// * STRING
  /// * BYTES
  /// * INTEGER
  /// * FLOAT
  /// * BOOLEAN
  /// * TIMESTAMP
  /// * DATE
  /// * TIME
  /// * DATETIME
  /// * GEOGRAPHY,
  /// * NUMERIC,
  /// * BIGNUMERIC,
  /// * RECORD
  /// (where RECORD indicates that the field contains a nested schema).
  public var type: Swift.String = Swift.String()

  /// The field mode. Possible values include NULLABLE, REQUIRED and
  /// REPEATED. The default value is NULLABLE.
  public var mode: Swift.String = Swift.String()

  /// Describes the nested schema fields if the type property is set
  /// to RECORD.
  public var fields: [TableFieldSchema] = []

  /// Initialize a new instance of `TableFieldSchema`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = TableFieldSchema().with { $0.field = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.TableFieldSchema"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
