// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Resource representation as defined by the corresponding service providing the
/// resource for a given API version.
public struct VersionedResource: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// API version of the resource.
  ///
  /// Example:
  /// If the resource is an instance provided by Compute Engine v1 API as defined
  /// in `https://cloud.google.com/compute/docs/reference/rest/v1/instances`,
  /// version will be "v1".
  public var version: Swift.String = Swift.String()

  /// JSON representation of the resource as defined by the corresponding
  /// service providing this resource.
  ///
  /// Example:
  /// If the resource is an instance provided by Compute Engine, this field will
  /// contain the JSON representation of the instance as defined by Compute
  /// Engine:
  /// `https://cloud.google.com/compute/docs/reference/rest/v1/instances`.
  ///
  /// You can find the resource definition for each supported resource type in
  /// this table:
  /// `https://cloud.google.com/asset-inventory/docs/supported-asset-types`
  public var resource: GoogleWKT.WKTStruct? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VersionedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VersionedResource().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let version = CodingKeys(stringValue: "version")
    static let resource = CodingKeys(stringValue: "resource")

    static let _knownKeys: Set<Swift.String> = [
      "version",
      "resource",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
      self.version = value
    }
    self.resource = try container.decodeIfPresent(GoogleWKT.WKTStruct.self, forKey: .resource)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.version, forKey: .version)
    try container.encodeIfPresent(self.resource, forKey: .resource)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.VersionedResource"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
