// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Resource representation as defined by the corresponding service providing the
/// resource for a given API version.
public struct VersionedResource: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// API version of the resource.
  ///
  /// Example:
  /// If the resource is an instance provided by Compute Engine v1 API as defined
  /// in `https://cloud.google.com/compute/docs/reference/rest/v1/instances`,
  /// version will be "v1".
  public var version: Swift.String = Swift.String()

  /// JSON representation of the resource as defined by the corresponding
  /// service providing this resource.
  ///
  /// Example:
  /// If the resource is an instance provided by Compute Engine, this field will
  /// contain the JSON representation of the instance as defined by Compute
  /// Engine:
  /// `https://cloud.google.com/compute/docs/reference/rest/v1/instances`.
  ///
  /// You can find the resource definition for each supported resource type in
  /// this table:
  /// `https://cloud.google.com/asset-inventory/docs/supported-asset-types`
  public var resource: GoogleCloudWKT.Struct? = nil

  /// Initialize a new instance of `VersionedResource`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VersionedResource().with { $0.version = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.asset.v1.VersionedResource"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
